# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

module Pangea
  module Resources
    module Splunk
      include SplunkInputsHttpEventCollector
      include SplunkIndexes
      include SplunkSavedSearches
      include SplunkAppsLocal
    end
  end
end
