# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_saved_event_types/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkSavedEventTypes
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_saved_event_types,
      attributes_class: Splunk::Types::SavedEventTypesAttributes,
      outputs: { id: :id },
      map: [:name, :search],
      map_present: [:acl, :color, :description, :priority, :tags],
      map_bool: [:disabled]
  end
  module Splunk
    include SplunkSavedEventTypes
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
