# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class SavedEventTypesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute :search, T::String
    attribute? :acl, T::Hash.optional
    attribute? :color, T::String.optional
    attribute? :description, T::String.optional
    attribute? :disabled, T::Bool.optional
    attribute? :priority, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
