# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_configs_conf/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkConfigsConf
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_configs_conf,
      attributes_class: Splunk::Types::ConfigsConfAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :variables]
  end
  module Splunk
    include SplunkConfigsConf
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
