# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_authentication_users/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkAuthenticationUsers
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_authentication_users,
      attributes_class: Splunk::Types::AuthenticationUsersAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:default_app, :email, :password, :realname, :roles, :tz],
      map_bool: [:force_change_pass, :restart_background_jobs]
  end
  module Splunk
    include SplunkAuthenticationUsers
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
