# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class AuthenticationUsersAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :default_app, T::String.optional
    attribute? :email, T::String.optional
    attribute? :force_change_pass, T::Bool.optional
    attribute? :password, T::String.optional
    attribute? :realname, T::String.optional
    attribute? :restart_background_jobs, T::Bool.optional
    attribute? :roles, T::Array.of(T::String).optional
    attribute? :tz, T::String.optional
  end
end
