# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_script/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsScript
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_script,
      attributes_class: Splunk::Types::InputsScriptAttributes,
      outputs: { id: :id },
      map: [:interval, :name],
      map_present: [:acl, :host, :index, :passauth, :rename_source, :source, :sourcetype],
      map_bool: [:disabled]
  end
  module Splunk
    include SplunkInputsScript
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
