# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_saved_searches/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkSavedSearches
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_saved_searches,
      attributes_class: Splunk::Types::SavedSearchesAttributes,
      outputs: { id: :id, name: :name },
      map: [:name, :search],
      map_present: [:action_email_to, :actions, :alert_comparator, :alert_threshold, :alert_type, :cron_schedule, :description, :dispatch_buckets, :dispatch_earliest_time, :dispatch_latest_time, :dispatch_max_count],
      map_bool: [:disabled, :is_scheduled, :is_visible]
  end
  module Splunk
    include SplunkSavedSearches
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
