# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class SavedSearchesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute :search, T::String
    attribute? :acl, T::Hash.optional
    attribute? :action_better_webhook_param_body_format, T::String.optional
    attribute? :action_better_webhook_param_credential, T::String.optional
    attribute? :action_better_webhook_param_credentials, T::String.optional
    attribute? :action_better_webhook_param_url, T::String.optional
    attribute? :action_create_xsoar_incident, T::String.optional
    attribute? :action_create_xsoar_incident_param_custom_fields, T::String.optional
    attribute? :action_create_xsoar_incident_param_details, T::String.optional
    attribute? :action_create_xsoar_incident_param_incident_name, T::String.optional
    attribute? :action_create_xsoar_incident_param_occurred, T::String.optional
    attribute? :action_create_xsoar_incident_param_send_all_servers, T::String.optional
    attribute? :action_create_xsoar_incident_param_server_url, T::String.optional
    attribute? :action_create_xsoar_incident_param_severity, T::String.optional
    attribute? :action_create_xsoar_incident_param_type, T::String.optional
    attribute? :action_email_auth_password, T::String.optional
    attribute? :action_email_auth_username, T::String.optional
    attribute? :action_email_bcc, T::String.optional
    attribute? :action_email_cc, T::String.optional
    attribute? :action_email_command, T::String.optional
    attribute? :action_email_format, T::String.optional
    attribute? :action_email_from, T::String.optional
    attribute? :action_email_hostname, T::String.optional
    attribute? :action_email_include_results_link, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_email_include_search, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_email_include_trigger, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_email_include_trigger_time, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_email_include_view_link, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_email_inline, T::Bool.optional
    attribute? :action_email_mailserver, T::String.optional
    attribute? :action_email_max_results, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_email_max_time, T::String.optional
    attribute? :action_email_message_alert, T::String.optional
    attribute? :action_email_message_report, T::String.optional
    attribute? :action_email_pdfview, T::String.optional
    attribute? :action_email_preprocess_results, T::String.optional
    attribute? :action_email_report_cid_font_list, T::String.optional
    attribute? :action_email_report_include_splunk_logo, T::Bool.optional
    attribute? :action_email_report_paper_orientation, T::String.optional
    attribute? :action_email_report_paper_size, T::String.optional
    attribute? :action_email_report_server_enabled, T::Bool.optional
    attribute? :action_email_report_server_url, T::String.optional
    attribute? :action_email_send_csv, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_email_send_pdf, T::Bool.optional
    attribute? :action_email_send_results, T::Bool.optional
    attribute? :action_email_subject, T::String.optional
    attribute? :action_email_to, T::String.optional
    attribute? :action_email_track_alert, T::Bool.optional
    attribute? :action_email_ttl, T::String.optional
    attribute? :action_email_use_ssl, T::Bool.optional
    attribute? :action_email_use_tls, T::Bool.optional
    attribute? :action_email_width_sort_columns, T::Bool.optional
    attribute? :action_jira_service_desk_param_account, T::String.optional
    attribute? :action_jira_service_desk_param_jira_customfields, T::String.optional
    attribute? :action_jira_service_desk_param_jira_description, T::String.optional
    attribute? :action_jira_service_desk_param_jira_issue_type, T::String.optional
    attribute? :action_jira_service_desk_param_jira_priority, T::String.optional
    attribute? :action_jira_service_desk_param_jira_project, T::String.optional
    attribute? :action_jira_service_desk_param_jira_summary, T::String.optional
    attribute? :action_logevent, T::String.optional
    attribute? :action_logevent_param_event, T::String.optional
    attribute? :action_logevent_param_host, T::String.optional
    attribute? :action_logevent_param_index, T::String.optional
    attribute? :action_logevent_param_source, T::String.optional
    attribute? :action_logevent_param_sourcetype, T::String.optional
    attribute? :action_pagerduty_custom_details, T::String.optional
    attribute? :action_pagerduty_integration_key, T::String.optional
    attribute? :action_pagerduty_integration_key_override, T::String.optional
    attribute? :action_pagerduty_integration_url, T::String.optional
    attribute? :action_pagerduty_integration_url_override, T::String.optional
    attribute? :action_populate_lookup_command, T::String.optional
    attribute? :action_populate_lookup_dest, T::String.optional
    attribute? :action_populate_lookup_hostname, T::String.optional
    attribute? :action_populate_lookup_max_results, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_populate_lookup_max_time, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_populate_lookup_track_alert, T::Bool.optional
    attribute? :action_populate_lookup_ttl, T::String.optional
    attribute? :action_rss_command, T::String.optional
    attribute? :action_rss_hostname, T::String.optional
    attribute? :action_rss_max_results, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_rss_max_time, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_rss_track_alert, T::Bool.optional
    attribute? :action_rss_ttl, T::String.optional
    attribute? :action_script_command, T::String.optional
    attribute? :action_script_filename, T::String.optional
    attribute? :action_script_hostname, T::String.optional
    attribute? :action_script_max_results, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_script_max_time, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_script_track_alert, T::Bool.optional
    attribute? :action_script_ttl, T::String.optional
    attribute? :action_slack_app_alert_integration_param_auto_join_channel, T::String.optional
    attribute? :action_slack_app_alert_integration_param_bot_username, T::String.optional
    attribute? :action_slack_app_alert_integration_param_channel, T::String.optional
    attribute? :action_slack_app_alert_integration_param_emoji, T::String.optional
    attribute? :action_slack_app_alert_integration_param_message, T::String.optional
    attribute? :action_slack_param_attachment, T::String.optional
    attribute? :action_slack_param_channel, T::String.optional
    attribute? :action_slack_param_fields, T::String.optional
    attribute? :action_slack_param_message, T::String.optional
    attribute? :action_slack_param_webhook_url_override, T::String.optional
    attribute? :action_snow_event_param_account, T::String.optional
    attribute? :action_snow_event_param_additional_info, T::String.optional
    attribute? :action_snow_event_param_ci_identifier, T::String.optional
    attribute? :action_snow_event_param_custom_fields, T::String.optional
    attribute? :action_snow_event_param_description, T::String.optional
    attribute? :action_snow_event_param_node, T::String.optional
    attribute? :action_snow_event_param_resource, T::String.optional
    attribute? :action_snow_event_param_severity, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_snow_event_param_type, T::String.optional
    attribute? :action_summary_index_command, T::String.optional
    attribute? :action_summary_index_hostname, T::String.optional
    attribute? :action_summary_index_inline, T::Bool.optional
    attribute? :action_summary_index_max_results, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_summary_index_max_time, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :action_summary_index_name, T::String.optional
    attribute? :action_summary_index_track_alert, T::Bool.optional
    attribute? :action_summary_index_ttl, T::String.optional
    attribute? :action_victorops_param_enable_recovery, T::String.optional
    attribute? :action_victorops_param_entity_id, T::String.optional
    attribute? :action_victorops_param_inactive_polls, T::String.optional
    attribute? :action_victorops_param_message_type, T::String.optional
    attribute? :action_victorops_param_monitoring_tool, T::String.optional
    attribute? :action_victorops_param_poll_interval, T::String.optional
    attribute? :action_victorops_param_record_id, T::String.optional
    attribute? :action_victorops_param_routing_key_override, T::String.optional
    attribute? :action_victorops_param_state_message, T::String.optional
    attribute? :action_webhook_param_url, T::String.optional
    attribute? :actions, T::String.optional
    attribute? :alert_comparator, T::String.optional
    attribute? :alert_condition, T::String.optional
    attribute? :alert_digest_mode, T::Bool.optional
    attribute? :alert_expires, T::String.optional
    attribute? :alert_severity, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :alert_suppress, T::Bool.optional
    attribute? :alert_suppress_fields, T::String.optional
    attribute? :alert_suppress_period, T::String.optional
    attribute? :alert_threshold, T::String.optional
    attribute? :alert_track, T::Bool.optional
    attribute? :alert_type, T::String.optional
    attribute? :allow_skew, T::String.optional
    attribute? :auto_summarize, T::Bool.optional
    attribute? :auto_summarize_command, T::String.optional
    attribute? :auto_summarize_cron_schedule, T::String.optional
    attribute? :auto_summarize_dispatch_earliest_time, T::String.optional
    attribute? :auto_summarize_dispatch_latest_time, T::String.optional
    attribute? :auto_summarize_dispatch_time_format, T::String.optional
    attribute? :auto_summarize_dispatch_ttl, T::String.optional
    attribute? :auto_summarize_max_disabled_buckets, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :auto_summarize_max_summary_ratio, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :auto_summarize_max_summary_size, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :auto_summarize_max_time, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :auto_summarize_suspend_period, T::String.optional
    attribute? :auto_summarize_timespan, T::String.optional
    attribute? :cron_schedule, T::String.optional
    attribute? :description, T::String.optional
    attribute? :disabled, T::Bool.optional
    attribute? :dispatch_buckets, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :dispatch_earliest_time, T::String.optional
    attribute? :dispatch_index_earliest, T::String.optional
    attribute? :dispatch_index_latest, T::String.optional
    attribute? :dispatch_indexed_realtime, T::Bool.optional
    attribute? :dispatch_indexed_realtime_minspan, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :dispatch_indexed_realtime_offset, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :dispatch_latest_time, T::String.optional
    attribute? :dispatch_lookups, T::Bool.optional
    attribute? :dispatch_max_count, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :dispatch_max_time, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :dispatch_reduce_freq, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :dispatch_rt_backfill, T::Bool.optional
    attribute? :dispatch_rt_maximum_span, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :dispatch_spawn_process, T::Bool.optional
    attribute? :dispatch_time_format, T::String.optional
    attribute? :dispatch_ttl, T::String.optional
    attribute? :display_view, T::String.optional
    attribute? :is_scheduled, T::Bool.optional
    attribute? :is_visible, T::Bool.optional
    attribute? :max_concurrent, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :realtime_schedule, T::Bool.optional
    attribute? :request_ui_dispatch_app, T::String.optional
    attribute? :request_ui_dispatch_view, T::String.optional
    attribute? :restart_on_searchpeer_add, T::Bool.optional
    attribute? :run_on_startup, T::Bool.optional
    attribute? :schedule_priority, T::String.optional
    attribute? :schedule_window, T::String.optional
    attribute? :vsid, T::String.optional
    attribute? :workload_pool, T::String.optional
  end
end
