# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/splunk_types'

module Pangea::Resources::Splunk::Types
  class SavedSearchesAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Splunk::Types

    attribute? :action_email_to, T::String.optional
    attribute? :actions, T::String.optional
    attribute? :alert_comparator, T::String.optional
    attribute? :alert_threshold, T::String.optional
    attribute? :alert_type, T::String.optional
    attribute? :cron_schedule, T::String.optional
    attribute? :description, T::String.optional
    attribute? :disabled, T::Bool.optional
    attribute? :dispatch_buckets, T::Integer.optional
    attribute? :dispatch_earliest_time, T::String.optional
    attribute? :dispatch_latest_time, T::String.optional
    attribute? :dispatch_max_count, T::Integer.optional
    attribute? :is_scheduled, T::Bool.optional
    attribute? :is_visible, T::Bool.optional
    attribute :name, T::String
    attribute :search, T::String
  end
end
