# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_monitor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsMonitor
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_monitor,
      attributes_class: Splunk::Types::InputsMonitorAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :blacklist, :crc_salt, :host, :host_regex, :host_segment, :ignore_older_than, :index, :rename_source, :sourcetype, :time_before_close, :whitelist],
      map_bool: [:disabled, :follow_tail, :recursive]
  end
  module Splunk
    include SplunkInputsMonitor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
