# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class InputsMonitorAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :blacklist, T::String.optional
    attribute? :crc_salt, T::String.optional
    attribute? :disabled, T::Bool.optional
    attribute? :follow_tail, T::Bool.optional
    attribute? :host, T::String.optional
    attribute? :host_regex, T::String.optional
    attribute? :host_segment, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :ignore_older_than, T::String.optional
    attribute? :index, T::String.optional
    attribute? :recursive, T::Bool.optional
    attribute? :rename_source, T::String.optional
    attribute? :sourcetype, T::String.optional
    attribute? :time_before_close, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :whitelist, T::String.optional
  end
end
