# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_tcp_splunk_tcp_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsTcpSplunkTcpToken
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_tcp_splunk_tcp_token,
      attributes_class: Splunk::Types::InputsTcpSplunkTcpTokenAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :token]
  end
  module Splunk
    include SplunkInputsTcpSplunkTcpToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
