# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class InputsTcpSplunkTcpTokenAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :token, T::String.optional
  end
end
