# Code generated by pangea-forge.
# InSpec profile for verifying splunk_generic_acl infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_generic_acl/ -t splunk://

control 'splunk_generic_acl-exists' do
  impact 1.0
  title 'Manages a splunk_generic_acl resource'
  desc 'Verify that the splunk_generic_acl resource exists and has expected properties'

  describe splunk_generic_acl(name: attribute('id')) do
    it { should exist }
    its('path') { should_not be_nil }
  end
end
