# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_data_ui_views/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkDataUiViews
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_data_ui_views,
      attributes_class: Splunk::Types::DataUiViewsAttributes,
      outputs: { id: :id },
      map: [:eai_data, :name],
      map_present: [:acl]
  end
  module Splunk
    include SplunkDataUiViews
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
