# Code generated by pangea-forge.
# InSpec profile for verifying splunk_saved_event_types infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_saved_event_types/ -t splunk://

control 'splunk_saved_event_types-exists' do
  impact 1.0
  title 'Manages a splunk_saved_event_types resource'
  desc 'Verify that the splunk_saved_event_types resource exists and has expected properties'

  describe splunk_saved_event_types(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('search') { should_not be_nil }
  end
end
