# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_outputs_tcp_syslog/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkOutputsTcpSyslog
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_outputs_tcp_syslog,
      attributes_class: Splunk::Types::OutputsTcpSyslogAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :priority, :server, :syslog_sourcetype, :timestamp_format, :type],
      map_bool: [:disabled]
  end
  module Splunk
    include SplunkOutputsTcpSyslog
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
