# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class OutputsTcpSyslogAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :disabled, T::Bool.optional
    attribute? :priority, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :server, T::String.optional
    attribute? :syslog_sourcetype, T::String.optional
    attribute? :timestamp_format, T::String.optional
    attribute? :type, T::String.optional
  end
end
