# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_http_event_collector/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsHttpEventCollector
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_http_event_collector,
      attributes_class: Splunk::Types::InputsHttpEventCollectorAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :host, :index, :indexes, :source, :sourcetype, :token, :use_ack],
      map_bool: [:disabled]
  end
  module Splunk
    include SplunkInputsHttpEventCollector
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
