# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/splunk_types'

module Pangea::Resources::Splunk::Types
  class InputsHttpEventCollectorAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Splunk::Types

    attribute? :disabled, T::Bool.optional
    attribute? :index, T::String.optional
    attribute? :indexes, T::Array.of(T::String).optional
    attribute :name, T::String
    attribute? :source, T::String.optional
    attribute? :sourcetype, T::String.optional
    attribute? :use_ack, T::Bool.optional
  end
end
