# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class InputsHttpEventCollectorAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :disabled, T::Bool.optional
    attribute? :host, T::String.optional
    attribute? :index, T::String.optional
    attribute? :indexes, T::Array.of(T::String).optional
    attribute? :source, T::String.optional
    attribute? :sourcetype, T::String.optional
    attribute? :token, T::String.optional
    attribute? :use_ack, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
