# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_lookup_table_file/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkLookupTableFile
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_lookup_table_file,
      attributes_class: Splunk::Types::LookupTableFileAttributes,
      outputs: { id: :id },
      map: [:app, :file_contents, :file_name, :owner]
  end
  module Splunk
    include SplunkLookupTableFile
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
