# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class LookupTableFileAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :app, T::String
    attribute :file_contents, T::Array.of(T::Array.of(T::String))
    attribute :file_name, T::String
    attribute :owner, T::String
  end
end
