# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_tcp_ssl/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsTcpSsl
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_tcp_ssl,
      attributes_class: Splunk::Types::InputsTcpSslAttributes,
      outputs: { id: :id },
      map_present: [:password, :root_ca, :server_cert],
      map_bool: [:disabled, :require_client_cert]
  end
  module Splunk
    include SplunkInputsTcpSsl
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
