# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class InputsTcpSslAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute? :disabled, T::Bool.optional
    attribute? :password, T::String.optional
    attribute? :require_client_cert, T::Bool.optional
    attribute? :root_ca, T::String.optional
    attribute? :server_cert, T::String.optional
  end
end
