# Code generated by pangea-forge.
# InSpec profile for verifying splunk_data_ui_views infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_data_ui_views/ -t splunk://

control 'splunk_data_ui_views-exists' do
  impact 1.0
  title 'Manages a splunk_data_ui_views resource'
  desc 'Verify that the splunk_data_ui_views resource exists and has expected properties'

  describe splunk_data_ui_views(name: attribute('id')) do
    it { should exist }
    its('eai_data') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
