# Code generated by pangea-forge.
# InSpec profile for verifying splunk_outputs_tcp_default infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_outputs_tcp_default/ -t splunk://

control 'splunk_outputs_tcp_default-exists' do
  impact 1.0
  title 'Manages a splunk_outputs_tcp_default resource'
  desc 'Verify that the splunk_outputs_tcp_default resource exists and has expected properties'

  describe splunk_outputs_tcp_default(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
