# Code generated by pangea-forge.
# InSpec profile for verifying splunk_lookup_definition infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_lookup_definition/ -t splunk://

control 'splunk_lookup_definition-exists' do
  impact 1.0
  title 'Manages a splunk_lookup_definition resource'
  desc 'Verify that the splunk_lookup_definition resource exists and has expected properties'

  describe splunk_lookup_definition(name: attribute('id')) do
    it { should exist }
    its('filename') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
