# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_admin_saml_groups/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkAdminSamlGroups
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_admin_saml_groups,
      attributes_class: Splunk::Types::AdminSamlGroupsAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:roles]
  end
  module Splunk
    include SplunkAdminSamlGroups
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
