# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class AdminSamlGroupsAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :roles, T::Array.of(T::String).optional
  end
end
