# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_tcp_cooked/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsTcpCooked
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_tcp_cooked,
      attributes_class: Splunk::Types::InputsTcpCookedAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :connection_host, :host, :restrict_to_host],
      map_bool: [:disabled]
  end
  module Splunk
    include SplunkInputsTcpCooked
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
