# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class InputsTcpCookedAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :connection_host, T::String.optional
    attribute? :disabled, T::Bool.optional
    attribute? :host, T::String.optional
    attribute? :restrict_to_host, T::String.optional
  end
end
