# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_sh_indexes_manager/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkShIndexesManager
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_sh_indexes_manager,
      attributes_class: Splunk::Types::ShIndexesManagerAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :datatype, :frozen_time_period_in_secs, :max_global_raw_data_size_mb]
  end
  module Splunk
    include SplunkShIndexesManager
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
