# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class ShIndexesManagerAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :datatype, T::String.optional
    attribute? :frozen_time_period_in_secs, T::String.optional
    attribute? :max_global_raw_data_size_mb, T::String.optional
  end
end
