# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_udp/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsUdp
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_udp,
      attributes_class: Splunk::Types::InputsUdpAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :connection_host, :host, :index, :queue, :restrict_to_host, :source, :sourcetype],
      map_bool: [:disabled, :no_appending_timestamp, :no_priority_stripping]
  end
  module Splunk
    include SplunkInputsUdp
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
