# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_inputs_tcp_raw/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkInputsTcpRaw
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_inputs_tcp_raw,
      attributes_class: Splunk::Types::InputsTcpRawAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :connection_host, :host, :index, :queue, :raw_tcp_done_timeout, :restrict_to_host, :source, :sourcetype],
      map_bool: [:disabled]
  end
  module Splunk
    include SplunkInputsTcpRaw
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
