# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class InputsTcpRawAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :connection_host, T::String.optional
    attribute? :disabled, T::Bool.optional
    attribute? :host, T::String.optional
    attribute? :index, T::String.optional
    attribute? :queue, T::String.optional
    attribute? :raw_tcp_done_timeout, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :restrict_to_host, T::String.optional
    attribute? :source, T::String.optional
    attribute? :sourcetype, T::String.optional
  end
end
