# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_outputs_tcp_server/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkOutputsTcpServer
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_outputs_tcp_server,
      attributes_class: Splunk::Types::OutputsTcpServerAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :method, :ssl_alt_name_to_check, :ssl_cert_path, :ssl_cipher, :ssl_common_name_to_check, :ssl_password, :ssl_root_ca_path],
      map_bool: [:disabled, :ssl_verify_server_cert]
  end
  module Splunk
    include SplunkOutputsTcpServer
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
