# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class OutputsTcpServerAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :disabled, T::Bool.optional
    attribute? :method, T::String.optional
    attribute? :ssl_alt_name_to_check, T::String.optional
    attribute? :ssl_cert_path, T::String.optional
    attribute? :ssl_cipher, T::String.optional
    attribute? :ssl_common_name_to_check, T::String.optional
    attribute? :ssl_password, T::String.optional
    attribute? :ssl_root_ca_path, T::String.optional
    attribute? :ssl_verify_server_cert, T::Bool.optional
  end
end
