# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea-core'
require 'terraform-synthesizer'

# Splunk types
require_relative 'pangea/types/splunk_types'

# Splunk resources
require_relative 'pangea/resources/splunk_inputs_http_event_collector/resource'
require_relative 'pangea/resources/splunk_indexes/resource'
require_relative 'pangea/resources/splunk_saved_searches/resource'
require_relative 'pangea/resources/splunk_apps_local/resource'

# Splunk module aggregator
require_relative 'pangea/resources/splunk'
