# Code generated by pangea-forge.
# InSpec profile for verifying splunk_inputs_tcp_ssl infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_inputs_tcp_ssl/ -t splunk://

control 'splunk_inputs_tcp_ssl-exists' do
  impact 1.0
  title 'Manages a splunk_inputs_tcp_ssl resource'
  desc 'Verify that the splunk_inputs_tcp_ssl resource exists and has expected properties'

  describe splunk_inputs_tcp_ssl(name: attribute('id')) do
    it { should exist }
  end
end
