# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_apps_local/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkAppsLocal
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_apps_local,
      attributes_class: Splunk::Types::AppsLocalAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :auth, :author, :description, :explicit_appname, :label, :session, :version],
      map_bool: [:configured, :filename, :update, :visible]
  end
  module Splunk
    include SplunkAppsLocal
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
