# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/splunk_types'

module Pangea::Resources::Splunk::Types
  class AppsLocalAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Splunk::Types

    attribute? :auth, T::String.optional
    attribute? :explicit_appname, T::String.optional
    attribute? :filename, T::Bool.optional
    attribute? :label, T::String.optional
    attribute :name, T::String
    attribute? :update, T::Bool.optional
    attribute? :visible, T::Bool.optional
  end
end
