# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class AppsLocalAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :auth, T::String.optional
    attribute? :author, T::String.optional
    attribute? :configured, T::Bool.optional
    attribute? :description, T::String.optional
    attribute? :explicit_appname, T::String.optional
    attribute? :filename, T::Bool.optional
    attribute? :label, T::String.optional
    attribute? :session, T::String.optional
    attribute? :update, T::Bool.optional
    attribute? :version, T::String.optional
    attribute? :visible, T::Bool.optional
  end
end
