# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_outputs_tcp_default/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkOutputsTcpDefault
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_outputs_tcp_default,
      attributes_class: Splunk::Types::OutputsTcpDefaultAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:acl, :default_group, :drop_events_on_queue_full, :heartbeat_frequency, :max_queue_size],
      map_bool: [:disabled, :index_and_forward, :send_cooked_data]
  end
  module Splunk
    include SplunkOutputsTcpDefault
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
