# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_authorization_roles/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkAuthorizationRoles
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_authorization_roles,
      attributes_class: Splunk::Types::AuthorizationRolesAttributes,
      outputs: { id: :id },
      map: [:name],
      map_present: [:capabilities, :cumulative_realtime_search_jobs_quota, :cumulative_search_jobs_quota, :default_app, :imported_roles, :realtime_search_jobs_quota, :search_disk_quota, :search_filter, :search_indexes_allowed, :search_indexes_default, :search_jobs_quota, :search_time_win]
  end
  module Splunk
    include SplunkAuthorizationRoles
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
