# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class AuthorizationRolesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :capabilities, T::Array.of(T::String).optional
    attribute? :cumulative_realtime_search_jobs_quota, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :cumulative_search_jobs_quota, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :default_app, T::String.optional
    attribute? :imported_roles, T::Array.of(T::String).optional
    attribute? :realtime_search_jobs_quota, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :search_disk_quota, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :search_filter, T::String.optional
    attribute? :search_indexes_allowed, T::Array.of(T::String).optional
    attribute? :search_indexes_default, T::Array.of(T::String).optional
    attribute? :search_jobs_quota, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :search_time_win, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
