# Code generated by pangea-forge.
# InSpec profile for verifying splunk_inputs_udp infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_inputs_udp/ -t splunk://

control 'splunk_inputs_udp-exists' do
  impact 1.0
  title 'Manages a splunk_inputs_udp resource'
  desc 'Verify that the splunk_inputs_udp resource exists and has expected properties'

  describe splunk_inputs_udp(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
