# Code generated by pangea-forge.
# InSpec profile for verifying splunk_lookup_table_file infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_lookup_table_file/ -t splunk://

control 'splunk_lookup_table_file-exists' do
  impact 1.0
  title 'Manages a splunk_lookup_table_file resource'
  desc 'Verify that the splunk_lookup_table_file resource exists and has expected properties'

  describe splunk_lookup_table_file(name: attribute('id')) do
    it { should exist }
    its('app') { should_not be_nil }
    its('file_contents') { should_not be_nil }
    its('file_name') { should_not be_nil }
    its('owner') { should_not be_nil }
  end
end
