# Code generated by pangea-forge.
# InSpec profile for verifying splunk_authentication_users infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_authentication_users/ -t splunk://

control 'splunk_authentication_users-exists' do
  impact 1.0
  title 'Manages a splunk_authentication_users resource'
  desc 'Verify that the splunk_authentication_users resource exists and has expected properties'

  describe splunk_authentication_users(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
