# Code generated by pangea-forge.
# InSpec profile for verifying splunk_admin_saml_groups infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_admin_saml_groups/ -t splunk://

control 'splunk_admin_saml_groups-exists' do
  impact 1.0
  title 'Manages a splunk_admin_saml_groups resource'
  desc 'Verify that the splunk_admin_saml_groups resource exists and has expected properties'

  describe splunk_admin_saml_groups(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
