# Code generated by pangea-forge.
# InSpec profile for verifying splunk_sh_indexes_manager infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_sh_indexes_manager/ -t splunk://

control 'splunk_sh_indexes_manager-exists' do
  impact 1.0
  title 'Manages a splunk_sh_indexes_manager resource'
  desc 'Verify that the splunk_sh_indexes_manager resource exists and has expected properties'

  describe splunk_sh_indexes_manager(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
  end
end
