# Code generated by pangea-forge.
# InSpec profile for verifying splunk_saved_searches infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_saved_searches/ -t splunk://

control 'splunk_saved_searches-exists' do
  impact 1.0
  title 'Manages a splunk_saved_searches resource'
  desc 'Verify that the splunk_saved_searches resource exists and has expected properties'

  describe splunk_saved_searches(name: attribute('id')) do
    it { should exist }
    its('name') { should_not be_nil }
    its('search') { should_not be_nil }
  end
end
