# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_generic_acl/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkGenericAcl
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_generic_acl,
      attributes_class: Splunk::Types::GenericAclAttributes,
      outputs: { id: :id },
      map: [:path],
      map_present: [:acl]
  end
  module Splunk
    include SplunkGenericAcl
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
