# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_lookup_definition/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkLookupDefinition
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_lookup_definition,
      attributes_class: Splunk::Types::LookupDefinitionAttributes,
      outputs: { id: :id },
      map: [:filename, :name],
      map_present: [:acl]
  end
  module Splunk
    include SplunkLookupDefinition
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
