# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_indexes/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkIndexes
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_indexes,
      attributes_class: Splunk::Types::IndexesAttributes,
      outputs: { id: :id, name: :name },
      map: [:name],
      map_present: [:cold_path, :cold_to_frozen_dir, :datatype, :frozen_time_period_in_secs, :home_path, :max_data_size_mb, :max_total_data_size_mb, :max_warm_db_count, :thawed_path],
      map_bool: []
  end
  module Splunk
    include SplunkIndexes
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
