# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class IndexesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute? :acl, T::Hash.optional
    attribute? :block_sign_size, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :bucket_rebuild_memory_hint, T::String.optional
    attribute? :cold_path, T::String.optional
    attribute? :cold_to_frozen_dir, T::String.optional
    attribute? :cold_to_frozen_script, T::String.optional
    attribute? :compress_rawdata, T::Bool.optional
    attribute? :datatype, T::String.optional
    attribute? :enable_online_bucket_repair, T::Bool.optional
    attribute? :frozen_time_period_in_secs, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :home_path, T::String.optional
    attribute? :max_bloom_backfill_bucket_age, T::String.optional
    attribute? :max_concurrent_optimizes, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_data_size, T::String.optional
    attribute? :max_hot_buckets, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_hot_idle_secs, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_hot_span_secs, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_mem_mb, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_meta_entries, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_time_unreplicated_no_acks, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_time_unreplicated_with_acks, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_total_data_size_mb, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_warm_db_count, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :min_raw_file_sync_secs, T::String.optional
    attribute? :min_stream_group_queue_size, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :partial_service_meta_period, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :process_tracker_service_interval, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :quarantine_future_secs, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :quarantine_past_secs, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :raw_chunk_size_bytes, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :rep_factor, T::String.optional
    attribute? :rotate_period_in_secs, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :service_meta_period, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :sync_meta, T::Bool.optional
    attribute? :thawed_path, T::String.optional
    attribute? :throttle_check_period, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :tstats_home_path, T::String.optional
    attribute? :warm_to_cold_script, T::String.optional
  end
end
