# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'
require 'pangea/types/splunk_types'

module Pangea::Resources::Splunk::Types
  class IndexesAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Splunk::Types

    attribute? :cold_path, T::String.optional
    attribute? :cold_to_frozen_dir, T::String.optional
    attribute? :datatype, T::String.optional
    attribute? :frozen_time_period_in_secs, T::Integer.optional
    attribute? :home_path, T::String.optional
    attribute? :max_data_size_mb, T::Integer.optional
    attribute? :max_total_data_size_mb, T::Integer.optional
    attribute? :max_warm_db_count, T::Integer.optional
    attribute :name, T::String
    attribute? :thawed_path, T::String.optional
  end
end
