# Code generated by pangea-forge.
# InSpec profile for verifying splunk_global_http_event_collector infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set SPLUNK_TOKEN and SPLUNK_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/splunk_global_http_event_collector/ -t splunk://

control 'splunk_global_http_event_collector-exists' do
  impact 1.0
  title 'Manages a splunk_global_http_event_collector resource'
  desc 'Verify that the splunk_global_http_event_collector resource exists and has expected properties'

  describe splunk_global_http_event_collector(name: attribute('id')) do
    it { should exist }
  end
end
