# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_outputs_tcp_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkOutputsTcpGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_outputs_tcp_group,
      attributes_class: Splunk::Types::OutputsTcpGroupAttributes,
      outputs: { id: :id },
      map: [:name, :servers],
      map_present: [:acl, :drop_events_on_queue_full, :heartbeat_frequency, :max_queue_size, :method, :token],
      map_bool: [:compressed, :disabled, :send_cooked_data]
  end
  module Splunk
    include SplunkOutputsTcpGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
