# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class OutputsTcpGroupAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute :name, T::String
    attribute :servers, T::Array.of(T::String)
    attribute? :acl, T::Hash.optional
    attribute? :compressed, T::Bool.optional
    attribute? :disabled, T::Bool.optional
    attribute? :drop_events_on_queue_full, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :heartbeat_frequency, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_queue_size, T::String.optional
    attribute? :method, T::String.optional
    attribute? :send_cooked_data, T::Bool.optional
    attribute? :token, T::String.optional
  end
end
