# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/splunk_global_http_event_collector/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module SplunkGlobalHttpEventCollector
    include Pangea::Resources::ResourceBuilder

    define_resource :splunk_global_http_event_collector,
      attributes_class: Splunk::Types::GlobalHttpEventCollectorAttributes,
      outputs: { id: :id },
      map_present: [:dedicated_io_threads, :max_sockets, :max_threads, :port, :use_deployment_server],
      map_bool: [:disabled, :enable_ssl]
  end
  module Splunk
    include SplunkGlobalHttpEventCollector
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Splunk)
