# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Splunk::Types
  include Dry.Types()

  class GlobalHttpEventCollectorAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Splunk::Types

    attribute? :dedicated_io_threads, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :disabled, T::Bool.optional
    attribute? :enable_ssl, T::Bool.optional
    attribute? :max_sockets, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :max_threads, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :port, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :use_deployment_server, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
