# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_inputs_udp resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkInputsUdp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_inputs_udp' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_udp('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_inputs_udp)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_udp('test', required_attrs)

        expect(ref.id).to eq("${splunk_inputs_udp.test.id}")
        expect(ref.connection_host).to eq("${splunk_inputs_udp.test.connection_host}")
        expect(ref.disabled).to eq("${splunk_inputs_udp.test.disabled}")
        expect(ref.host).to eq("${splunk_inputs_udp.test.host}")
        expect(ref.index).to eq("${splunk_inputs_udp.test.index}")
        expect(ref.no_appending_timestamp).to eq("${splunk_inputs_udp.test.no_appending_timestamp}")
        expect(ref.no_priority_stripping).to eq("${splunk_inputs_udp.test.no_priority_stripping}")
        expect(ref.queue).to eq("${splunk_inputs_udp.test.queue}")
        expect(ref.restrict_to_host).to eq("${splunk_inputs_udp.test.restrict_to_host}")
        expect(ref.source).to eq("${splunk_inputs_udp.test.source}")
        expect(ref.sourcetype).to eq("${splunk_inputs_udp.test.sourcetype}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_udp', 'test')
        expect(config).not_to have_key('connection_host')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('index')
        expect(config).not_to have_key('no_appending_timestamp')
        expect(config).not_to have_key('no_priority_stripping')
        expect(config).not_to have_key('queue')
        expect(config).not_to have_key('restrict_to_host')
        expect(config).not_to have_key('source')
        expect(config).not_to have_key('sourcetype')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, connection_host: 'test-value', disabled: true, host: 'test-value', index: 'test-value', no_appending_timestamp: true, no_priority_stripping: true, queue: 'test-value', restrict_to_host: 'test-value', source: 'test-value', sourcetype: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_udp', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('connection_host')
        expect(config).to have_key('disabled')
        expect(config).to have_key('host')
        expect(config).to have_key('index')
        expect(config).to have_key('no_appending_timestamp')
        expect(config).to have_key('no_priority_stripping')
        expect(config).to have_key('queue')
        expect(config).to have_key('restrict_to_host')
        expect(config).to have_key('source')
        expect(config).to have_key('sourcetype')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes connection_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(connection_host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('connection_host')
      end

      it 'omits connection_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('connection_host')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes index when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(index: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('index')
      end

      it 'omits index when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('index')
      end
      it 'includes no_appending_timestamp when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(no_appending_timestamp: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('no_appending_timestamp')
      end

      it 'omits no_appending_timestamp when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('no_appending_timestamp')
      end
      it 'includes no_priority_stripping when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(no_priority_stripping: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('no_priority_stripping')
      end

      it 'omits no_priority_stripping when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('no_priority_stripping')
      end
      it 'includes queue when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(queue: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('queue')
      end

      it 'omits queue when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('queue')
      end
      it 'includes restrict_to_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(restrict_to_host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('restrict_to_host')
      end

      it 'omits restrict_to_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('restrict_to_host')
      end
      it 'includes source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(source: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('source')
      end

      it 'omits source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('source')
      end
      it 'includes sourcetype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('opt', required_attrs.merge(sourcetype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'opt')
        expect(config).to have_key('sourcetype')
      end

      it 'omits sourcetype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_udp', 'minimal')
        expect(config).not_to have_key('sourcetype')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_inputs_udp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_udp', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts no_appending_timestamp=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(no_appending_timestamp: val)
          synth.splunk_inputs_udp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_udp', "bool_#{val}")
          expect(config['no_appending_timestamp']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts no_priority_stripping=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(no_priority_stripping: val)
          synth.splunk_inputs_udp("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_udp', "bool_#{val}")
          expect(config['no_priority_stripping']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_udp', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_udp('first', required_attrs)
        synth.splunk_inputs_udp('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_inputs_udp')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_inputs_udp,
    method: :splunk_inputs_udp,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :connection_host, :disabled, :host, :index, :no_appending_timestamp, :no_priority_stripping, :queue, :restrict_to_host, :source, :sourcetype],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled, :no_appending_timestamp, :no_priority_stripping]
end
