# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_authentication_users resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkAuthenticationUsers do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_authentication_users' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_authentication_users('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_authentication_users)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_authentication_users('test', required_attrs)

        expect(ref.id).to eq("${splunk_authentication_users.test.id}")
        expect(ref.default_app).to eq("${splunk_authentication_users.test.default_app}")
        expect(ref.email).to eq("${splunk_authentication_users.test.email}")
        expect(ref.realname).to eq("${splunk_authentication_users.test.realname}")
        expect(ref.restart_background_jobs).to eq("${splunk_authentication_users.test.restart_background_jobs}")
        expect(ref.roles).to eq("${splunk_authentication_users.test.roles}")
        expect(ref.tz).to eq("${splunk_authentication_users.test.tz}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_authentication_users', 'test')
        expect(config).not_to have_key('default_app')
        expect(config).not_to have_key('email')
        expect(config).not_to have_key('realname')
        expect(config).not_to have_key('restart_background_jobs')
        expect(config).not_to have_key('roles')
        expect(config).not_to have_key('tz')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ default_app: 'test-value', email: 'test-value', force_change_pass: true, password: 'test-value', realname: 'test-value', restart_background_jobs: true, roles: ['test-value'], tz: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_authentication_users', 'full')
        expect(config).to have_key('default_app')
        expect(config).to have_key('email')
        expect(config).to have_key('force_change_pass')
        expect(config).to have_key('password')
        expect(config).to have_key('realname')
        expect(config).to have_key('restart_background_jobs')
        expect(config).to have_key('roles')
        expect(config).to have_key('tz')
      end
    end

    context 'optional attributes' do
      it 'includes default_app when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(default_app: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('default_app')
      end

      it 'omits default_app when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('default_app')
      end
      it 'includes email when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(email: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('email')
      end

      it 'omits email when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('email')
      end
      it 'includes force_change_pass when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(force_change_pass: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('force_change_pass')
      end

      it 'omits force_change_pass when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('force_change_pass')
      end
      it 'includes password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('password')
      end

      it 'omits password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('password')
      end
      it 'includes realname when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(realname: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('realname')
      end

      it 'omits realname when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('realname')
      end
      it 'includes restart_background_jobs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(restart_background_jobs: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('restart_background_jobs')
      end

      it 'omits restart_background_jobs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('restart_background_jobs')
      end
      it 'includes roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('roles')
      end

      it 'omits roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('roles')
      end
      it 'includes tz when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('opt', required_attrs.merge(tz: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'opt')
        expect(config).to have_key('tz')
      end

      it 'omits tz when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authentication_users', 'minimal')
        expect(config).not_to have_key('tz')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts force_change_pass=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force_change_pass: val)
          synth.splunk_authentication_users("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_authentication_users', "bool_#{val}")
          expect(config['force_change_pass']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts restart_background_jobs=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(restart_background_jobs: val)
          synth.splunk_authentication_users("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_authentication_users', "bool_#{val}")
          expect(config['restart_background_jobs']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_authentication_users', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authentication_users('first', required_attrs)
        synth.splunk_authentication_users('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_authentication_users')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_authentication_users,
    method: :splunk_authentication_users,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :default_app, :email, :realname, :restart_background_jobs, :roles, :tz],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: [:force_change_pass, :restart_background_jobs]
end
