# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_authorization_roles resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkAuthorizationRoles do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_authorization_roles' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_authorization_roles('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_authorization_roles)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_authorization_roles('test', required_attrs)

        expect(ref.id).to eq("${splunk_authorization_roles.test.id}")
        expect(ref.capabilities).to eq("${splunk_authorization_roles.test.capabilities}")
        expect(ref.default_app).to eq("${splunk_authorization_roles.test.default_app}")
        expect(ref.imported_roles).to eq("${splunk_authorization_roles.test.imported_roles}")
        expect(ref.search_filter).to eq("${splunk_authorization_roles.test.search_filter}")
        expect(ref.search_indexes_allowed).to eq("${splunk_authorization_roles.test.search_indexes_allowed}")
        expect(ref.search_indexes_default).to eq("${splunk_authorization_roles.test.search_indexes_default}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_authorization_roles', 'test')
        expect(config).not_to have_key('capabilities')
        expect(config).not_to have_key('default_app')
        expect(config).not_to have_key('imported_roles')
        expect(config).not_to have_key('search_filter')
        expect(config).not_to have_key('search_indexes_allowed')
        expect(config).not_to have_key('search_indexes_default')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ capabilities: ['test-value'], cumulative_realtime_search_jobs_quota: 3.14, cumulative_search_jobs_quota: 3.14, default_app: 'test-value', imported_roles: ['test-value'], realtime_search_jobs_quota: 3.14, search_disk_quota: 3.14, search_filter: 'test-value', search_indexes_allowed: ['test-value'], search_indexes_default: ['test-value'], search_jobs_quota: 3.14, search_time_win: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_authorization_roles', 'full')
        expect(config).to have_key('capabilities')
        expect(config).to have_key('cumulative_realtime_search_jobs_quota')
        expect(config).to have_key('cumulative_search_jobs_quota')
        expect(config).to have_key('default_app')
        expect(config).to have_key('imported_roles')
        expect(config).to have_key('realtime_search_jobs_quota')
        expect(config).to have_key('search_disk_quota')
        expect(config).to have_key('search_filter')
        expect(config).to have_key('search_indexes_allowed')
        expect(config).to have_key('search_indexes_default')
        expect(config).to have_key('search_jobs_quota')
        expect(config).to have_key('search_time_win')
      end
    end

    context 'optional attributes' do
      it 'includes capabilities when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(capabilities: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('capabilities')
      end

      it 'omits capabilities when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('capabilities')
      end
      it 'includes cumulative_realtime_search_jobs_quota when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(cumulative_realtime_search_jobs_quota: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('cumulative_realtime_search_jobs_quota')
      end

      it 'omits cumulative_realtime_search_jobs_quota when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('cumulative_realtime_search_jobs_quota')
      end
      it 'includes cumulative_search_jobs_quota when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(cumulative_search_jobs_quota: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('cumulative_search_jobs_quota')
      end

      it 'omits cumulative_search_jobs_quota when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('cumulative_search_jobs_quota')
      end
      it 'includes default_app when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(default_app: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('default_app')
      end

      it 'omits default_app when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('default_app')
      end
      it 'includes imported_roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(imported_roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('imported_roles')
      end

      it 'omits imported_roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('imported_roles')
      end
      it 'includes realtime_search_jobs_quota when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(realtime_search_jobs_quota: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('realtime_search_jobs_quota')
      end

      it 'omits realtime_search_jobs_quota when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('realtime_search_jobs_quota')
      end
      it 'includes search_disk_quota when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(search_disk_quota: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('search_disk_quota')
      end

      it 'omits search_disk_quota when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('search_disk_quota')
      end
      it 'includes search_filter when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(search_filter: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('search_filter')
      end

      it 'omits search_filter when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('search_filter')
      end
      it 'includes search_indexes_allowed when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(search_indexes_allowed: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('search_indexes_allowed')
      end

      it 'omits search_indexes_allowed when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('search_indexes_allowed')
      end
      it 'includes search_indexes_default when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(search_indexes_default: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('search_indexes_default')
      end

      it 'omits search_indexes_default when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('search_indexes_default')
      end
      it 'includes search_jobs_quota when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(search_jobs_quota: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('search_jobs_quota')
      end

      it 'omits search_jobs_quota when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('search_jobs_quota')
      end
      it 'includes search_time_win when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('opt', required_attrs.merge(search_time_win: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'opt')
        expect(config).to have_key('search_time_win')
      end

      it 'omits search_time_win when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_authorization_roles', 'minimal')
        expect(config).not_to have_key('search_time_win')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_authorization_roles', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_authorization_roles('first', required_attrs)
        synth.splunk_authorization_roles('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_authorization_roles')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_authorization_roles,
    method: :splunk_authorization_roles,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :capabilities, :default_app, :imported_roles, :search_filter, :search_indexes_allowed, :search_indexes_default],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
