# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_inputs_monitor resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkInputsMonitor do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_inputs_monitor' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_monitor('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_inputs_monitor)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_monitor('test', required_attrs)

        expect(ref.id).to eq("${splunk_inputs_monitor.test.id}")
        expect(ref.blacklist).to eq("${splunk_inputs_monitor.test.blacklist}")
        expect(ref.crc_salt).to eq("${splunk_inputs_monitor.test.crc_salt}")
        expect(ref.disabled).to eq("${splunk_inputs_monitor.test.disabled}")
        expect(ref.follow_tail).to eq("${splunk_inputs_monitor.test.follow_tail}")
        expect(ref.host).to eq("${splunk_inputs_monitor.test.host}")
        expect(ref.host_regex).to eq("${splunk_inputs_monitor.test.host_regex}")
        expect(ref.host_segment).to eq("${splunk_inputs_monitor.test.host_segment}")
        expect(ref.ignore_older_than).to eq("${splunk_inputs_monitor.test.ignore_older_than}")
        expect(ref.index).to eq("${splunk_inputs_monitor.test.index}")
        expect(ref.recursive).to eq("${splunk_inputs_monitor.test.recursive}")
        expect(ref.rename_source).to eq("${splunk_inputs_monitor.test.rename_source}")
        expect(ref.sourcetype).to eq("${splunk_inputs_monitor.test.sourcetype}")
        expect(ref.time_before_close).to eq("${splunk_inputs_monitor.test.time_before_close}")
        expect(ref.whitelist).to eq("${splunk_inputs_monitor.test.whitelist}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'test')
        expect(config).not_to have_key('blacklist')
        expect(config).not_to have_key('crc_salt')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('follow_tail')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('host_regex')
        expect(config).not_to have_key('host_segment')
        expect(config).not_to have_key('ignore_older_than')
        expect(config).not_to have_key('index')
        expect(config).not_to have_key('recursive')
        expect(config).not_to have_key('rename_source')
        expect(config).not_to have_key('sourcetype')
        expect(config).not_to have_key('time_before_close')
        expect(config).not_to have_key('whitelist')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, blacklist: 'test-value', crc_salt: 'test-value', disabled: true, follow_tail: true, host: 'test-value', host_regex: 'test-value', host_segment: 3.14, ignore_older_than: 'test-value', index: 'test-value', recursive: true, rename_source: 'test-value', sourcetype: 'test-value', time_before_close: 3.14, whitelist: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('blacklist')
        expect(config).to have_key('crc_salt')
        expect(config).to have_key('disabled')
        expect(config).to have_key('follow_tail')
        expect(config).to have_key('host')
        expect(config).to have_key('host_regex')
        expect(config).to have_key('host_segment')
        expect(config).to have_key('ignore_older_than')
        expect(config).to have_key('index')
        expect(config).to have_key('recursive')
        expect(config).to have_key('rename_source')
        expect(config).to have_key('sourcetype')
        expect(config).to have_key('time_before_close')
        expect(config).to have_key('whitelist')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes blacklist when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(blacklist: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('blacklist')
      end

      it 'omits blacklist when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('blacklist')
      end
      it 'includes crc_salt when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(crc_salt: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('crc_salt')
      end

      it 'omits crc_salt when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('crc_salt')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes follow_tail when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(follow_tail: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('follow_tail')
      end

      it 'omits follow_tail when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('follow_tail')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes host_regex when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(host_regex: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('host_regex')
      end

      it 'omits host_regex when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('host_regex')
      end
      it 'includes host_segment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(host_segment: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('host_segment')
      end

      it 'omits host_segment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('host_segment')
      end
      it 'includes ignore_older_than when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(ignore_older_than: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('ignore_older_than')
      end

      it 'omits ignore_older_than when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('ignore_older_than')
      end
      it 'includes index when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(index: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('index')
      end

      it 'omits index when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('index')
      end
      it 'includes recursive when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(recursive: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('recursive')
      end

      it 'omits recursive when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('recursive')
      end
      it 'includes rename_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(rename_source: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('rename_source')
      end

      it 'omits rename_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('rename_source')
      end
      it 'includes sourcetype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(sourcetype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('sourcetype')
      end

      it 'omits sourcetype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('sourcetype')
      end
      it 'includes time_before_close when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(time_before_close: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('time_before_close')
      end

      it 'omits time_before_close when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('time_before_close')
      end
      it 'includes whitelist when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('opt', required_attrs.merge(whitelist: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'opt')
        expect(config).to have_key('whitelist')
      end

      it 'omits whitelist when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'minimal')
        expect(config).not_to have_key('whitelist')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_inputs_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_monitor', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts follow_tail=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(follow_tail: val)
          synth.splunk_inputs_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_monitor', "bool_#{val}")
          expect(config['follow_tail']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts recursive=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(recursive: val)
          synth.splunk_inputs_monitor("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_monitor', "bool_#{val}")
          expect(config['recursive']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_monitor', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_monitor('first', required_attrs)
        synth.splunk_inputs_monitor('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_inputs_monitor')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_inputs_monitor,
    method: :splunk_inputs_monitor,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :blacklist, :crc_salt, :disabled, :follow_tail, :host, :host_regex, :host_segment, :ignore_older_than, :index, :recursive, :rename_source, :sourcetype, :time_before_close, :whitelist],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled, :follow_tail, :recursive]
end
