# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_inputs_tcp_cooked resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkInputsTcpCooked do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_inputs_tcp_cooked' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_tcp_cooked('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_inputs_tcp_cooked)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_tcp_cooked('test', required_attrs)

        expect(ref.id).to eq("${splunk_inputs_tcp_cooked.test.id}")
        expect(ref.connection_host).to eq("${splunk_inputs_tcp_cooked.test.connection_host}")
        expect(ref.disabled).to eq("${splunk_inputs_tcp_cooked.test.disabled}")
        expect(ref.host).to eq("${splunk_inputs_tcp_cooked.test.host}")
        expect(ref.restrict_to_host).to eq("${splunk_inputs_tcp_cooked.test.restrict_to_host}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'test')
        expect(config).not_to have_key('connection_host')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('restrict_to_host')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, connection_host: 'test-value', disabled: true, host: 'test-value', restrict_to_host: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('connection_host')
        expect(config).to have_key('disabled')
        expect(config).to have_key('host')
        expect(config).to have_key('restrict_to_host')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes connection_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('opt', required_attrs.merge(connection_host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'opt')
        expect(config).to have_key('connection_host')
      end

      it 'omits connection_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'minimal')
        expect(config).not_to have_key('connection_host')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes restrict_to_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('opt', required_attrs.merge(restrict_to_host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'opt')
        expect(config).to have_key('restrict_to_host')
      end

      it 'omits restrict_to_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'minimal')
        expect(config).not_to have_key('restrict_to_host')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_inputs_tcp_cooked("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_cooked', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_cooked('first', required_attrs)
        synth.splunk_inputs_tcp_cooked('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_inputs_tcp_cooked')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_inputs_tcp_cooked,
    method: :splunk_inputs_tcp_cooked,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :connection_host, :disabled, :host, :restrict_to_host],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled]
end
