# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_inputs_http_event_collector resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkInputsHttpEventCollector do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_inputs_http_event_collector' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_http_event_collector('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_inputs_http_event_collector)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_http_event_collector('test', required_attrs)

        expect(ref.id).to eq("${splunk_inputs_http_event_collector.test.id}")
        expect(ref.disabled).to eq("${splunk_inputs_http_event_collector.test.disabled}")
        expect(ref.host).to eq("${splunk_inputs_http_event_collector.test.host}")
        expect(ref.index).to eq("${splunk_inputs_http_event_collector.test.index}")
        expect(ref.indexes).to eq("${splunk_inputs_http_event_collector.test.indexes}")
        expect(ref.source).to eq("${splunk_inputs_http_event_collector.test.source}")
        expect(ref.sourcetype).to eq("${splunk_inputs_http_event_collector.test.sourcetype}")
        expect(ref.token).to eq("${splunk_inputs_http_event_collector.test.token}")
        expect(ref.use_ack).to eq("${splunk_inputs_http_event_collector.test.use_ack}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'test')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('index')
        expect(config).not_to have_key('indexes')
        expect(config).not_to have_key('source')
        expect(config).not_to have_key('sourcetype')
        expect(config).not_to have_key('token')
        expect(config).not_to have_key('use_ack')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, disabled: true, host: 'test-value', index: 'test-value', indexes: ['test-value'], source: 'test-value', sourcetype: 'test-value', token: 'test-value', use_ack: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('disabled')
        expect(config).to have_key('host')
        expect(config).to have_key('index')
        expect(config).to have_key('indexes')
        expect(config).to have_key('source')
        expect(config).to have_key('sourcetype')
        expect(config).to have_key('token')
        expect(config).to have_key('use_ack')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes index when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(index: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('index')
      end

      it 'omits index when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('index')
      end
      it 'includes indexes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(indexes: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('indexes')
      end

      it 'omits indexes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('indexes')
      end
      it 'includes source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(source: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('source')
      end

      it 'omits source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('source')
      end
      it 'includes sourcetype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(sourcetype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('sourcetype')
      end

      it 'omits sourcetype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('sourcetype')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('token')
      end
      it 'includes use_ack when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('opt', required_attrs.merge(use_ack: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'opt')
        expect(config).to have_key('use_ack')
      end

      it 'omits use_ack when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'minimal')
        expect(config).not_to have_key('use_ack')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_inputs_http_event_collector("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_http_event_collector', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_http_event_collector('first', required_attrs)
        synth.splunk_inputs_http_event_collector('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_inputs_http_event_collector')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_inputs_http_event_collector,
    method: :splunk_inputs_http_event_collector,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :disabled, :host, :index, :indexes, :source, :sourcetype, :token, :use_ack],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled]
end
