# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_saved_event_types resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkSavedEventTypes do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', search: 'test-value' } }

  describe ':splunk_saved_event_types' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'test')
        validate_required_attributes(config, [:name, :search])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_saved_event_types('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_saved_event_types)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_saved_event_types('test', required_attrs)

        expect(ref.id).to eq("${splunk_saved_event_types.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, color: 'test-value', description: 'test-value', disabled: true, priority: 3.14, tags: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_saved_event_types', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('color')
        expect(config).to have_key('description')
        expect(config).to have_key('disabled')
        expect(config).to have_key('priority')
        expect(config).to have_key('tags')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes color when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('opt', required_attrs.merge(color: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'opt')
        expect(config).to have_key('color')
      end

      it 'omits color when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'minimal')
        expect(config).not_to have_key('color')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes priority when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('opt', required_attrs.merge(priority: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'opt')
        expect(config).to have_key('priority')
      end

      it 'omits priority when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'minimal')
        expect(config).not_to have_key('priority')
      end
      it 'includes tags when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('opt', required_attrs.merge(tags: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'opt')
        expect(config).to have_key('tags')
      end

      it 'omits tags when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_saved_event_types', 'minimal')
        expect(config).not_to have_key('tags')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_saved_event_types("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_saved_event_types', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_saved_event_types', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['search']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_saved_event_types('first', required_attrs)
        synth.splunk_saved_event_types('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_saved_event_types')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_saved_event_types,
    method: :splunk_saved_event_types,
    required_attrs: { name: 'test-value', search: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled]
end
