# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_indexes resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkIndexes do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_indexes' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_indexes', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_indexes('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_indexes)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_indexes('test', required_attrs)

        expect(ref.id).to eq("${splunk_indexes.test.id}")
        expect(ref.block_sign_size).to eq("${splunk_indexes.test.block_sign_size}")
        expect(ref.bucket_rebuild_memory_hint).to eq("${splunk_indexes.test.bucket_rebuild_memory_hint}")
        expect(ref.cold_path).to eq("${splunk_indexes.test.cold_path}")
        expect(ref.cold_to_frozen_dir).to eq("${splunk_indexes.test.cold_to_frozen_dir}")
        expect(ref.cold_to_frozen_script).to eq("${splunk_indexes.test.cold_to_frozen_script}")
        expect(ref.compress_rawdata).to eq("${splunk_indexes.test.compress_rawdata}")
        expect(ref.datatype).to eq("${splunk_indexes.test.datatype}")
        expect(ref.enable_online_bucket_repair).to eq("${splunk_indexes.test.enable_online_bucket_repair}")
        expect(ref.frozen_time_period_in_secs).to eq("${splunk_indexes.test.frozen_time_period_in_secs}")
        expect(ref.home_path).to eq("${splunk_indexes.test.home_path}")
        expect(ref.max_bloom_backfill_bucket_age).to eq("${splunk_indexes.test.max_bloom_backfill_bucket_age}")
        expect(ref.max_concurrent_optimizes).to eq("${splunk_indexes.test.max_concurrent_optimizes}")
        expect(ref.max_data_size).to eq("${splunk_indexes.test.max_data_size}")
        expect(ref.max_hot_buckets).to eq("${splunk_indexes.test.max_hot_buckets}")
        expect(ref.max_hot_idle_secs).to eq("${splunk_indexes.test.max_hot_idle_secs}")
        expect(ref.max_hot_span_secs).to eq("${splunk_indexes.test.max_hot_span_secs}")
        expect(ref.max_mem_mb).to eq("${splunk_indexes.test.max_mem_mb}")
        expect(ref.max_meta_entries).to eq("${splunk_indexes.test.max_meta_entries}")
        expect(ref.max_time_unreplicated_no_acks).to eq("${splunk_indexes.test.max_time_unreplicated_no_acks}")
        expect(ref.max_time_unreplicated_with_acks).to eq("${splunk_indexes.test.max_time_unreplicated_with_acks}")
        expect(ref.max_total_data_size_mb).to eq("${splunk_indexes.test.max_total_data_size_mb}")
        expect(ref.max_warm_db_count).to eq("${splunk_indexes.test.max_warm_db_count}")
        expect(ref.min_raw_file_sync_secs).to eq("${splunk_indexes.test.min_raw_file_sync_secs}")
        expect(ref.min_stream_group_queue_size).to eq("${splunk_indexes.test.min_stream_group_queue_size}")
        expect(ref.partial_service_meta_period).to eq("${splunk_indexes.test.partial_service_meta_period}")
        expect(ref.process_tracker_service_interval).to eq("${splunk_indexes.test.process_tracker_service_interval}")
        expect(ref.quarantine_future_secs).to eq("${splunk_indexes.test.quarantine_future_secs}")
        expect(ref.quarantine_past_secs).to eq("${splunk_indexes.test.quarantine_past_secs}")
        expect(ref.raw_chunk_size_bytes).to eq("${splunk_indexes.test.raw_chunk_size_bytes}")
        expect(ref.rep_factor).to eq("${splunk_indexes.test.rep_factor}")
        expect(ref.rotate_period_in_secs).to eq("${splunk_indexes.test.rotate_period_in_secs}")
        expect(ref.service_meta_period).to eq("${splunk_indexes.test.service_meta_period}")
        expect(ref.sync_meta).to eq("${splunk_indexes.test.sync_meta}")
        expect(ref.thawed_path).to eq("${splunk_indexes.test.thawed_path}")
        expect(ref.throttle_check_period).to eq("${splunk_indexes.test.throttle_check_period}")
        expect(ref.tstats_home_path).to eq("${splunk_indexes.test.tstats_home_path}")
        expect(ref.warm_to_cold_script).to eq("${splunk_indexes.test.warm_to_cold_script}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_indexes', 'test')
        expect(config).not_to have_key('block_sign_size')
        expect(config).not_to have_key('bucket_rebuild_memory_hint')
        expect(config).not_to have_key('cold_path')
        expect(config).not_to have_key('cold_to_frozen_dir')
        expect(config).not_to have_key('cold_to_frozen_script')
        expect(config).not_to have_key('compress_rawdata')
        expect(config).not_to have_key('datatype')
        expect(config).not_to have_key('enable_online_bucket_repair')
        expect(config).not_to have_key('frozen_time_period_in_secs')
        expect(config).not_to have_key('home_path')
        expect(config).not_to have_key('max_bloom_backfill_bucket_age')
        expect(config).not_to have_key('max_concurrent_optimizes')
        expect(config).not_to have_key('max_data_size')
        expect(config).not_to have_key('max_hot_buckets')
        expect(config).not_to have_key('max_hot_idle_secs')
        expect(config).not_to have_key('max_hot_span_secs')
        expect(config).not_to have_key('max_mem_mb')
        expect(config).not_to have_key('max_meta_entries')
        expect(config).not_to have_key('max_time_unreplicated_no_acks')
        expect(config).not_to have_key('max_time_unreplicated_with_acks')
        expect(config).not_to have_key('max_total_data_size_mb')
        expect(config).not_to have_key('max_warm_db_count')
        expect(config).not_to have_key('min_raw_file_sync_secs')
        expect(config).not_to have_key('min_stream_group_queue_size')
        expect(config).not_to have_key('partial_service_meta_period')
        expect(config).not_to have_key('process_tracker_service_interval')
        expect(config).not_to have_key('quarantine_future_secs')
        expect(config).not_to have_key('quarantine_past_secs')
        expect(config).not_to have_key('raw_chunk_size_bytes')
        expect(config).not_to have_key('rep_factor')
        expect(config).not_to have_key('rotate_period_in_secs')
        expect(config).not_to have_key('service_meta_period')
        expect(config).not_to have_key('sync_meta')
        expect(config).not_to have_key('thawed_path')
        expect(config).not_to have_key('throttle_check_period')
        expect(config).not_to have_key('tstats_home_path')
        expect(config).not_to have_key('warm_to_cold_script')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, block_sign_size: 3.14, bucket_rebuild_memory_hint: 'test-value', cold_path: 'test-value', cold_to_frozen_dir: 'test-value', cold_to_frozen_script: 'test-value', compress_rawdata: true, datatype: 'test-value', enable_online_bucket_repair: true, frozen_time_period_in_secs: 3.14, home_path: 'test-value', max_bloom_backfill_bucket_age: 'test-value', max_concurrent_optimizes: 3.14, max_data_size: 'test-value', max_hot_buckets: 3.14, max_hot_idle_secs: 3.14, max_hot_span_secs: 3.14, max_mem_mb: 3.14, max_meta_entries: 3.14, max_time_unreplicated_no_acks: 3.14, max_time_unreplicated_with_acks: 3.14, max_total_data_size_mb: 3.14, max_warm_db_count: 3.14, min_raw_file_sync_secs: 'test-value', min_stream_group_queue_size: 3.14, partial_service_meta_period: 3.14, process_tracker_service_interval: 3.14, quarantine_future_secs: 3.14, quarantine_past_secs: 3.14, raw_chunk_size_bytes: 3.14, rep_factor: 'test-value', rotate_period_in_secs: 3.14, service_meta_period: 3.14, sync_meta: true, thawed_path: 'test-value', throttle_check_period: 3.14, tstats_home_path: 'test-value', warm_to_cold_script: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_indexes', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('block_sign_size')
        expect(config).to have_key('bucket_rebuild_memory_hint')
        expect(config).to have_key('cold_path')
        expect(config).to have_key('cold_to_frozen_dir')
        expect(config).to have_key('cold_to_frozen_script')
        expect(config).to have_key('compress_rawdata')
        expect(config).to have_key('datatype')
        expect(config).to have_key('enable_online_bucket_repair')
        expect(config).to have_key('frozen_time_period_in_secs')
        expect(config).to have_key('home_path')
        expect(config).to have_key('max_bloom_backfill_bucket_age')
        expect(config).to have_key('max_concurrent_optimizes')
        expect(config).to have_key('max_data_size')
        expect(config).to have_key('max_hot_buckets')
        expect(config).to have_key('max_hot_idle_secs')
        expect(config).to have_key('max_hot_span_secs')
        expect(config).to have_key('max_mem_mb')
        expect(config).to have_key('max_meta_entries')
        expect(config).to have_key('max_time_unreplicated_no_acks')
        expect(config).to have_key('max_time_unreplicated_with_acks')
        expect(config).to have_key('max_total_data_size_mb')
        expect(config).to have_key('max_warm_db_count')
        expect(config).to have_key('min_raw_file_sync_secs')
        expect(config).to have_key('min_stream_group_queue_size')
        expect(config).to have_key('partial_service_meta_period')
        expect(config).to have_key('process_tracker_service_interval')
        expect(config).to have_key('quarantine_future_secs')
        expect(config).to have_key('quarantine_past_secs')
        expect(config).to have_key('raw_chunk_size_bytes')
        expect(config).to have_key('rep_factor')
        expect(config).to have_key('rotate_period_in_secs')
        expect(config).to have_key('service_meta_period')
        expect(config).to have_key('sync_meta')
        expect(config).to have_key('thawed_path')
        expect(config).to have_key('throttle_check_period')
        expect(config).to have_key('tstats_home_path')
        expect(config).to have_key('warm_to_cold_script')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes block_sign_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(block_sign_size: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('block_sign_size')
      end

      it 'omits block_sign_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('block_sign_size')
      end
      it 'includes bucket_rebuild_memory_hint when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(bucket_rebuild_memory_hint: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('bucket_rebuild_memory_hint')
      end

      it 'omits bucket_rebuild_memory_hint when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('bucket_rebuild_memory_hint')
      end
      it 'includes cold_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(cold_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('cold_path')
      end

      it 'omits cold_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('cold_path')
      end
      it 'includes cold_to_frozen_dir when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(cold_to_frozen_dir: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('cold_to_frozen_dir')
      end

      it 'omits cold_to_frozen_dir when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('cold_to_frozen_dir')
      end
      it 'includes cold_to_frozen_script when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(cold_to_frozen_script: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('cold_to_frozen_script')
      end

      it 'omits cold_to_frozen_script when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('cold_to_frozen_script')
      end
      it 'includes compress_rawdata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(compress_rawdata: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('compress_rawdata')
      end

      it 'omits compress_rawdata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('compress_rawdata')
      end
      it 'includes datatype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(datatype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('datatype')
      end

      it 'omits datatype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('datatype')
      end
      it 'includes enable_online_bucket_repair when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(enable_online_bucket_repair: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('enable_online_bucket_repair')
      end

      it 'omits enable_online_bucket_repair when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('enable_online_bucket_repair')
      end
      it 'includes frozen_time_period_in_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(frozen_time_period_in_secs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('frozen_time_period_in_secs')
      end

      it 'omits frozen_time_period_in_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('frozen_time_period_in_secs')
      end
      it 'includes home_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(home_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('home_path')
      end

      it 'omits home_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('home_path')
      end
      it 'includes max_bloom_backfill_bucket_age when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_bloom_backfill_bucket_age: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_bloom_backfill_bucket_age')
      end

      it 'omits max_bloom_backfill_bucket_age when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_bloom_backfill_bucket_age')
      end
      it 'includes max_concurrent_optimizes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_concurrent_optimizes: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_concurrent_optimizes')
      end

      it 'omits max_concurrent_optimizes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_concurrent_optimizes')
      end
      it 'includes max_data_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_data_size: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_data_size')
      end

      it 'omits max_data_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_data_size')
      end
      it 'includes max_hot_buckets when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_hot_buckets: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_hot_buckets')
      end

      it 'omits max_hot_buckets when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_hot_buckets')
      end
      it 'includes max_hot_idle_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_hot_idle_secs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_hot_idle_secs')
      end

      it 'omits max_hot_idle_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_hot_idle_secs')
      end
      it 'includes max_hot_span_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_hot_span_secs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_hot_span_secs')
      end

      it 'omits max_hot_span_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_hot_span_secs')
      end
      it 'includes max_mem_mb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_mem_mb: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_mem_mb')
      end

      it 'omits max_mem_mb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_mem_mb')
      end
      it 'includes max_meta_entries when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_meta_entries: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_meta_entries')
      end

      it 'omits max_meta_entries when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_meta_entries')
      end
      it 'includes max_time_unreplicated_no_acks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_time_unreplicated_no_acks: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_time_unreplicated_no_acks')
      end

      it 'omits max_time_unreplicated_no_acks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_time_unreplicated_no_acks')
      end
      it 'includes max_time_unreplicated_with_acks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_time_unreplicated_with_acks: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_time_unreplicated_with_acks')
      end

      it 'omits max_time_unreplicated_with_acks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_time_unreplicated_with_acks')
      end
      it 'includes max_total_data_size_mb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_total_data_size_mb: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_total_data_size_mb')
      end

      it 'omits max_total_data_size_mb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_total_data_size_mb')
      end
      it 'includes max_warm_db_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(max_warm_db_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('max_warm_db_count')
      end

      it 'omits max_warm_db_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('max_warm_db_count')
      end
      it 'includes min_raw_file_sync_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(min_raw_file_sync_secs: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('min_raw_file_sync_secs')
      end

      it 'omits min_raw_file_sync_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('min_raw_file_sync_secs')
      end
      it 'includes min_stream_group_queue_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(min_stream_group_queue_size: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('min_stream_group_queue_size')
      end

      it 'omits min_stream_group_queue_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('min_stream_group_queue_size')
      end
      it 'includes partial_service_meta_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(partial_service_meta_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('partial_service_meta_period')
      end

      it 'omits partial_service_meta_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('partial_service_meta_period')
      end
      it 'includes process_tracker_service_interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(process_tracker_service_interval: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('process_tracker_service_interval')
      end

      it 'omits process_tracker_service_interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('process_tracker_service_interval')
      end
      it 'includes quarantine_future_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(quarantine_future_secs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('quarantine_future_secs')
      end

      it 'omits quarantine_future_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('quarantine_future_secs')
      end
      it 'includes quarantine_past_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(quarantine_past_secs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('quarantine_past_secs')
      end

      it 'omits quarantine_past_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('quarantine_past_secs')
      end
      it 'includes raw_chunk_size_bytes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(raw_chunk_size_bytes: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('raw_chunk_size_bytes')
      end

      it 'omits raw_chunk_size_bytes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('raw_chunk_size_bytes')
      end
      it 'includes rep_factor when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(rep_factor: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('rep_factor')
      end

      it 'omits rep_factor when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('rep_factor')
      end
      it 'includes rotate_period_in_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(rotate_period_in_secs: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('rotate_period_in_secs')
      end

      it 'omits rotate_period_in_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('rotate_period_in_secs')
      end
      it 'includes service_meta_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(service_meta_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('service_meta_period')
      end

      it 'omits service_meta_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('service_meta_period')
      end
      it 'includes sync_meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(sync_meta: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('sync_meta')
      end

      it 'omits sync_meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('sync_meta')
      end
      it 'includes thawed_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(thawed_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('thawed_path')
      end

      it 'omits thawed_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('thawed_path')
      end
      it 'includes throttle_check_period when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(throttle_check_period: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('throttle_check_period')
      end

      it 'omits throttle_check_period when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('throttle_check_period')
      end
      it 'includes tstats_home_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(tstats_home_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('tstats_home_path')
      end

      it 'omits tstats_home_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('tstats_home_path')
      end
      it 'includes warm_to_cold_script when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('opt', required_attrs.merge(warm_to_cold_script: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'opt')
        expect(config).to have_key('warm_to_cold_script')
      end

      it 'omits warm_to_cold_script when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_indexes', 'minimal')
        expect(config).not_to have_key('warm_to_cold_script')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts compress_rawdata=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(compress_rawdata: val)
          synth.splunk_indexes("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_indexes', "bool_#{val}")
          expect(config['compress_rawdata']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_online_bucket_repair=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_online_bucket_repair: val)
          synth.splunk_indexes("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_indexes', "bool_#{val}")
          expect(config['enable_online_bucket_repair']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts sync_meta=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(sync_meta: val)
          synth.splunk_indexes("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_indexes', "bool_#{val}")
          expect(config['sync_meta']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_indexes', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_indexes('first', required_attrs)
        synth.splunk_indexes('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_indexes')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_indexes,
    method: :splunk_indexes,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :block_sign_size, :bucket_rebuild_memory_hint, :cold_path, :cold_to_frozen_dir, :cold_to_frozen_script, :compress_rawdata, :datatype, :enable_online_bucket_repair, :frozen_time_period_in_secs, :home_path, :max_bloom_backfill_bucket_age, :max_concurrent_optimizes, :max_data_size, :max_hot_buckets, :max_hot_idle_secs, :max_hot_span_secs, :max_mem_mb, :max_meta_entries, :max_time_unreplicated_no_acks, :max_time_unreplicated_with_acks, :max_total_data_size_mb, :max_warm_db_count, :min_raw_file_sync_secs, :min_stream_group_queue_size, :partial_service_meta_period, :process_tracker_service_interval, :quarantine_future_secs, :quarantine_past_secs, :raw_chunk_size_bytes, :rep_factor, :rotate_period_in_secs, :service_meta_period, :sync_meta, :thawed_path, :throttle_check_period, :tstats_home_path, :warm_to_cold_script],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:compress_rawdata, :enable_online_bucket_repair, :sync_meta]
end
