# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_outputs_tcp_syslog resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkOutputsTcpSyslog do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_outputs_tcp_syslog' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_outputs_tcp_syslog('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_outputs_tcp_syslog)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_outputs_tcp_syslog('test', required_attrs)

        expect(ref.id).to eq("${splunk_outputs_tcp_syslog.test.id}")
        expect(ref.disabled).to eq("${splunk_outputs_tcp_syslog.test.disabled}")
        expect(ref.priority).to eq("${splunk_outputs_tcp_syslog.test.priority}")
        expect(ref.server).to eq("${splunk_outputs_tcp_syslog.test.server}")
        expect(ref.syslog_sourcetype).to eq("${splunk_outputs_tcp_syslog.test.syslog_sourcetype}")
        expect(ref.timestamp_format).to eq("${splunk_outputs_tcp_syslog.test.timestamp_format}")
        expect(ref.type).to eq("${splunk_outputs_tcp_syslog.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'test')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('priority')
        expect(config).not_to have_key('server')
        expect(config).not_to have_key('syslog_sourcetype')
        expect(config).not_to have_key('timestamp_format')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, disabled: true, priority: 3.14, server: 'test-value', syslog_sourcetype: 'test-value', timestamp_format: 'test-value', type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('disabled')
        expect(config).to have_key('priority')
        expect(config).to have_key('server')
        expect(config).to have_key('syslog_sourcetype')
        expect(config).to have_key('timestamp_format')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes priority when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('opt', required_attrs.merge(priority: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'opt')
        expect(config).to have_key('priority')
      end

      it 'omits priority when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'minimal')
        expect(config).not_to have_key('priority')
      end
      it 'includes server when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('opt', required_attrs.merge(server: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'opt')
        expect(config).to have_key('server')
      end

      it 'omits server when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'minimal')
        expect(config).not_to have_key('server')
      end
      it 'includes syslog_sourcetype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('opt', required_attrs.merge(syslog_sourcetype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'opt')
        expect(config).to have_key('syslog_sourcetype')
      end

      it 'omits syslog_sourcetype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'minimal')
        expect(config).not_to have_key('syslog_sourcetype')
      end
      it 'includes timestamp_format when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('opt', required_attrs.merge(timestamp_format: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'opt')
        expect(config).to have_key('timestamp_format')
      end

      it 'omits timestamp_format when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'minimal')
        expect(config).not_to have_key('timestamp_format')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_outputs_tcp_syslog("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_syslog', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_syslog('first', required_attrs)
        synth.splunk_outputs_tcp_syslog('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_outputs_tcp_syslog')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_outputs_tcp_syslog,
    method: :splunk_outputs_tcp_syslog,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :disabled, :priority, :server, :syslog_sourcetype, :timestamp_format, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled]
end
