# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_outputs_tcp_default resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkOutputsTcpDefault do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_outputs_tcp_default' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_outputs_tcp_default('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_outputs_tcp_default)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_outputs_tcp_default('test', required_attrs)

        expect(ref.id).to eq("${splunk_outputs_tcp_default.test.id}")
        expect(ref.default_group).to eq("${splunk_outputs_tcp_default.test.default_group}")
        expect(ref.disabled).to eq("${splunk_outputs_tcp_default.test.disabled}")
        expect(ref.drop_events_on_queue_full).to eq("${splunk_outputs_tcp_default.test.drop_events_on_queue_full}")
        expect(ref.heartbeat_frequency).to eq("${splunk_outputs_tcp_default.test.heartbeat_frequency}")
        expect(ref.index_and_forward).to eq("${splunk_outputs_tcp_default.test.index_and_forward}")
        expect(ref.max_queue_size).to eq("${splunk_outputs_tcp_default.test.max_queue_size}")
        expect(ref.send_cooked_data).to eq("${splunk_outputs_tcp_default.test.send_cooked_data}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'test')
        expect(config).not_to have_key('default_group')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('drop_events_on_queue_full')
        expect(config).not_to have_key('heartbeat_frequency')
        expect(config).not_to have_key('index_and_forward')
        expect(config).not_to have_key('max_queue_size')
        expect(config).not_to have_key('send_cooked_data')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, default_group: 'test-value', disabled: true, drop_events_on_queue_full: 3.14, heartbeat_frequency: 3.14, index_and_forward: true, max_queue_size: 'test-value', send_cooked_data: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('default_group')
        expect(config).to have_key('disabled')
        expect(config).to have_key('drop_events_on_queue_full')
        expect(config).to have_key('heartbeat_frequency')
        expect(config).to have_key('index_and_forward')
        expect(config).to have_key('max_queue_size')
        expect(config).to have_key('send_cooked_data')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes default_group when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(default_group: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('default_group')
      end

      it 'omits default_group when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('default_group')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes drop_events_on_queue_full when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(drop_events_on_queue_full: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('drop_events_on_queue_full')
      end

      it 'omits drop_events_on_queue_full when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('drop_events_on_queue_full')
      end
      it 'includes heartbeat_frequency when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(heartbeat_frequency: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('heartbeat_frequency')
      end

      it 'omits heartbeat_frequency when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('heartbeat_frequency')
      end
      it 'includes index_and_forward when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(index_and_forward: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('index_and_forward')
      end

      it 'omits index_and_forward when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('index_and_forward')
      end
      it 'includes max_queue_size when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(max_queue_size: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('max_queue_size')
      end

      it 'omits max_queue_size when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('max_queue_size')
      end
      it 'includes send_cooked_data when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('opt', required_attrs.merge(send_cooked_data: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'opt')
        expect(config).to have_key('send_cooked_data')
      end

      it 'omits send_cooked_data when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'minimal')
        expect(config).not_to have_key('send_cooked_data')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_outputs_tcp_default("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_outputs_tcp_default', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts index_and_forward=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(index_and_forward: val)
          synth.splunk_outputs_tcp_default("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_outputs_tcp_default', "bool_#{val}")
          expect(config['index_and_forward']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts send_cooked_data=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(send_cooked_data: val)
          synth.splunk_outputs_tcp_default("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_outputs_tcp_default', "bool_#{val}")
          expect(config['send_cooked_data']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_default', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_default('first', required_attrs)
        synth.splunk_outputs_tcp_default('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_outputs_tcp_default')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_outputs_tcp_default,
    method: :splunk_outputs_tcp_default,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :default_group, :disabled, :drop_events_on_queue_full, :heartbeat_frequency, :index_and_forward, :max_queue_size, :send_cooked_data],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled, :index_and_forward, :send_cooked_data]
end
