# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_outputs_tcp_server resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkOutputsTcpServer do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_outputs_tcp_server' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_outputs_tcp_server('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_outputs_tcp_server)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_outputs_tcp_server('test', required_attrs)

        expect(ref.id).to eq("${splunk_outputs_tcp_server.test.id}")
        expect(ref.disabled).to eq("${splunk_outputs_tcp_server.test.disabled}")
        expect(ref.method).to eq("${splunk_outputs_tcp_server.test.method}")
        expect(ref.ssl_alt_name_to_check).to eq("${splunk_outputs_tcp_server.test.ssl_alt_name_to_check}")
        expect(ref.ssl_cert_path).to eq("${splunk_outputs_tcp_server.test.ssl_cert_path}")
        expect(ref.ssl_cipher).to eq("${splunk_outputs_tcp_server.test.ssl_cipher}")
        expect(ref.ssl_common_name_to_check).to eq("${splunk_outputs_tcp_server.test.ssl_common_name_to_check}")
        expect(ref.ssl_password).to eq("${splunk_outputs_tcp_server.test.ssl_password}")
        expect(ref.ssl_root_ca_path).to eq("${splunk_outputs_tcp_server.test.ssl_root_ca_path}")
        expect(ref.ssl_verify_server_cert).to eq("${splunk_outputs_tcp_server.test.ssl_verify_server_cert}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'test')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('method')
        expect(config).not_to have_key('ssl_alt_name_to_check')
        expect(config).not_to have_key('ssl_cert_path')
        expect(config).not_to have_key('ssl_cipher')
        expect(config).not_to have_key('ssl_common_name_to_check')
        expect(config).not_to have_key('ssl_password')
        expect(config).not_to have_key('ssl_root_ca_path')
        expect(config).not_to have_key('ssl_verify_server_cert')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, disabled: true, method: 'test-value', ssl_alt_name_to_check: 'test-value', ssl_cert_path: 'test-value', ssl_cipher: 'test-value', ssl_common_name_to_check: 'test-value', ssl_password: 'test-value', ssl_root_ca_path: 'test-value', ssl_verify_server_cert: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('disabled')
        expect(config).to have_key('method')
        expect(config).to have_key('ssl_alt_name_to_check')
        expect(config).to have_key('ssl_cert_path')
        expect(config).to have_key('ssl_cipher')
        expect(config).to have_key('ssl_common_name_to_check')
        expect(config).to have_key('ssl_password')
        expect(config).to have_key('ssl_root_ca_path')
        expect(config).to have_key('ssl_verify_server_cert')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(method: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('method')
      end

      it 'omits method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('method')
      end
      it 'includes ssl_alt_name_to_check when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(ssl_alt_name_to_check: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('ssl_alt_name_to_check')
      end

      it 'omits ssl_alt_name_to_check when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('ssl_alt_name_to_check')
      end
      it 'includes ssl_cert_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(ssl_cert_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('ssl_cert_path')
      end

      it 'omits ssl_cert_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('ssl_cert_path')
      end
      it 'includes ssl_cipher when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(ssl_cipher: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('ssl_cipher')
      end

      it 'omits ssl_cipher when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('ssl_cipher')
      end
      it 'includes ssl_common_name_to_check when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(ssl_common_name_to_check: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('ssl_common_name_to_check')
      end

      it 'omits ssl_common_name_to_check when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('ssl_common_name_to_check')
      end
      it 'includes ssl_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(ssl_password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('ssl_password')
      end

      it 'omits ssl_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('ssl_password')
      end
      it 'includes ssl_root_ca_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(ssl_root_ca_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('ssl_root_ca_path')
      end

      it 'omits ssl_root_ca_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('ssl_root_ca_path')
      end
      it 'includes ssl_verify_server_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('opt', required_attrs.merge(ssl_verify_server_cert: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'opt')
        expect(config).to have_key('ssl_verify_server_cert')
      end

      it 'omits ssl_verify_server_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'minimal')
        expect(config).not_to have_key('ssl_verify_server_cert')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:ssl_password]
        expect(sensitive_fields).to include(:ssl_password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_outputs_tcp_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_outputs_tcp_server', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ssl_verify_server_cert=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ssl_verify_server_cert: val)
          synth.splunk_outputs_tcp_server("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_outputs_tcp_server', "bool_#{val}")
          expect(config['ssl_verify_server_cert']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_outputs_tcp_server', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_outputs_tcp_server('first', required_attrs)
        synth.splunk_outputs_tcp_server('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_outputs_tcp_server')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_outputs_tcp_server,
    method: :splunk_outputs_tcp_server,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :disabled, :method, :ssl_alt_name_to_check, :ssl_cert_path, :ssl_cipher, :ssl_common_name_to_check, :ssl_password, :ssl_root_ca_path, :ssl_verify_server_cert],
    sensitive_fields: [:ssl_password],
    immutable_fields: [],
    boolean_fields: [:disabled, :ssl_verify_server_cert]
end
