# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_global_http_event_collector resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkGlobalHttpEventCollector do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':splunk_global_http_event_collector' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_global_http_event_collector('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_global_http_event_collector)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_global_http_event_collector('test', required_attrs)

        expect(ref.id).to eq("${splunk_global_http_event_collector.test.id}")
        expect(ref.dedicated_io_threads).to eq("${splunk_global_http_event_collector.test.dedicated_io_threads}")
        expect(ref.disabled).to eq("${splunk_global_http_event_collector.test.disabled}")
        expect(ref.enable_ssl).to eq("${splunk_global_http_event_collector.test.enable_ssl}")
        expect(ref.max_sockets).to eq("${splunk_global_http_event_collector.test.max_sockets}")
        expect(ref.max_threads).to eq("${splunk_global_http_event_collector.test.max_threads}")
        expect(ref.port).to eq("${splunk_global_http_event_collector.test.port}")
        expect(ref.use_deployment_server).to eq("${splunk_global_http_event_collector.test.use_deployment_server}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'test')
        expect(config).not_to have_key('dedicated_io_threads')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('enable_ssl')
        expect(config).not_to have_key('max_sockets')
        expect(config).not_to have_key('max_threads')
        expect(config).not_to have_key('port')
        expect(config).not_to have_key('use_deployment_server')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ dedicated_io_threads: 3.14, disabled: true, enable_ssl: true, max_sockets: 3.14, max_threads: 3.14, port: 3.14, use_deployment_server: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'full')
        expect(config).to have_key('dedicated_io_threads')
        expect(config).to have_key('disabled')
        expect(config).to have_key('enable_ssl')
        expect(config).to have_key('max_sockets')
        expect(config).to have_key('max_threads')
        expect(config).to have_key('port')
        expect(config).to have_key('use_deployment_server')
      end
    end

    context 'optional attributes' do
      it 'includes dedicated_io_threads when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('opt', required_attrs.merge(dedicated_io_threads: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'opt')
        expect(config).to have_key('dedicated_io_threads')
      end

      it 'omits dedicated_io_threads when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'minimal')
        expect(config).not_to have_key('dedicated_io_threads')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes enable_ssl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('opt', required_attrs.merge(enable_ssl: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'opt')
        expect(config).to have_key('enable_ssl')
      end

      it 'omits enable_ssl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'minimal')
        expect(config).not_to have_key('enable_ssl')
      end
      it 'includes max_sockets when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('opt', required_attrs.merge(max_sockets: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'opt')
        expect(config).to have_key('max_sockets')
      end

      it 'omits max_sockets when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'minimal')
        expect(config).not_to have_key('max_sockets')
      end
      it 'includes max_threads when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('opt', required_attrs.merge(max_threads: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'opt')
        expect(config).to have_key('max_threads')
      end

      it 'omits max_threads when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'minimal')
        expect(config).not_to have_key('max_threads')
      end
      it 'includes port when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('opt', required_attrs.merge(port: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'opt')
        expect(config).to have_key('port')
      end

      it 'omits port when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'minimal')
        expect(config).not_to have_key('port')
      end
      it 'includes use_deployment_server when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('opt', required_attrs.merge(use_deployment_server: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'opt')
        expect(config).to have_key('use_deployment_server')
      end

      it 'omits use_deployment_server when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'minimal')
        expect(config).not_to have_key('use_deployment_server')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_global_http_event_collector("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_global_http_event_collector', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_ssl=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_ssl: val)
          synth.splunk_global_http_event_collector("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_global_http_event_collector', "bool_#{val}")
          expect(config['enable_ssl']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_global_http_event_collector', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_global_http_event_collector('first', required_attrs)
        synth.splunk_global_http_event_collector('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_global_http_event_collector')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_global_http_event_collector,
    method: :splunk_global_http_event_collector,
    required_attrs: {},
    expected_outputs: [:id, :dedicated_io_threads, :disabled, :enable_ssl, :max_sockets, :max_threads, :port, :use_deployment_server],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled, :enable_ssl]
end
