# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_inputs_tcp_ssl resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkInputsTcpSsl do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':splunk_inputs_tcp_ssl' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_tcp_ssl('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_inputs_tcp_ssl)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_tcp_ssl('test', required_attrs)

        expect(ref.id).to eq("${splunk_inputs_tcp_ssl.test.id}")
        expect(ref.disabled).to eq("${splunk_inputs_tcp_ssl.test.disabled}")
        expect(ref.password).to eq("${splunk_inputs_tcp_ssl.test.password}")
        expect(ref.require_client_cert).to eq("${splunk_inputs_tcp_ssl.test.require_client_cert}")
        expect(ref.root_ca).to eq("${splunk_inputs_tcp_ssl.test.root_ca}")
        expect(ref.server_cert).to eq("${splunk_inputs_tcp_ssl.test.server_cert}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'test')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('password')
        expect(config).not_to have_key('require_client_cert')
        expect(config).not_to have_key('root_ca')
        expect(config).not_to have_key('server_cert')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ disabled: true, password: 'test-value', require_client_cert: true, root_ca: 'test-value', server_cert: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'full')
        expect(config).to have_key('disabled')
        expect(config).to have_key('password')
        expect(config).to have_key('require_client_cert')
        expect(config).to have_key('root_ca')
        expect(config).to have_key('server_cert')
      end
    end

    context 'optional attributes' do
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('opt', required_attrs.merge(password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'opt')
        expect(config).to have_key('password')
      end

      it 'omits password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'minimal')
        expect(config).not_to have_key('password')
      end
      it 'includes require_client_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('opt', required_attrs.merge(require_client_cert: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'opt')
        expect(config).to have_key('require_client_cert')
      end

      it 'omits require_client_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'minimal')
        expect(config).not_to have_key('require_client_cert')
      end
      it 'includes root_ca when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('opt', required_attrs.merge(root_ca: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'opt')
        expect(config).to have_key('root_ca')
      end

      it 'omits root_ca when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'minimal')
        expect(config).not_to have_key('root_ca')
      end
      it 'includes server_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('opt', required_attrs.merge(server_cert: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'opt')
        expect(config).to have_key('server_cert')
      end

      it 'omits server_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'minimal')
        expect(config).not_to have_key('server_cert')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_inputs_tcp_ssl("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts require_client_cert=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(require_client_cert: val)
          synth.splunk_inputs_tcp_ssl("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', "bool_#{val}")
          expect(config['require_client_cert']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_ssl', 'typed')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_ssl('first', required_attrs)
        synth.splunk_inputs_tcp_ssl('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_inputs_tcp_ssl')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_inputs_tcp_ssl,
    method: :splunk_inputs_tcp_ssl,
    required_attrs: {},
    expected_outputs: [:id, :disabled, :password, :require_client_cert, :root_ca, :server_cert],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: [:disabled, :require_client_cert]
end
