# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_apps_local resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkAppsLocal do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_apps_local' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_apps_local', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_apps_local('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_apps_local)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_apps_local('test', required_attrs)

        expect(ref.id).to eq("${splunk_apps_local.test.id}")
        expect(ref.author).to eq("${splunk_apps_local.test.author}")
        expect(ref.configured).to eq("${splunk_apps_local.test.configured}")
        expect(ref.description).to eq("${splunk_apps_local.test.description}")
        expect(ref.label).to eq("${splunk_apps_local.test.label}")
        expect(ref.version).to eq("${splunk_apps_local.test.version}")
        expect(ref.visible).to eq("${splunk_apps_local.test.visible}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_apps_local', 'test')
        expect(config).not_to have_key('author')
        expect(config).not_to have_key('configured')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('label')
        expect(config).not_to have_key('version')
        expect(config).not_to have_key('visible')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, auth: 'test-value', author: 'test-value', configured: true, description: 'test-value', explicit_appname: 'test-value', filename: true, label: 'test-value', session: 'test-value', update: true, version: 'test-value', visible: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_apps_local', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('auth')
        expect(config).to have_key('author')
        expect(config).to have_key('configured')
        expect(config).to have_key('description')
        expect(config).to have_key('explicit_appname')
        expect(config).to have_key('filename')
        expect(config).to have_key('label')
        expect(config).to have_key('session')
        expect(config).to have_key('update')
        expect(config).to have_key('version')
        expect(config).to have_key('visible')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes auth when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(auth: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('auth')
      end

      it 'omits auth when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('auth')
      end
      it 'includes author when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(author: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('author')
      end

      it 'omits author when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('author')
      end
      it 'includes configured when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(configured: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('configured')
      end

      it 'omits configured when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('configured')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes explicit_appname when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(explicit_appname: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('explicit_appname')
      end

      it 'omits explicit_appname when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('explicit_appname')
      end
      it 'includes filename when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(filename: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('filename')
      end

      it 'omits filename when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('filename')
      end
      it 'includes label when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(label: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('label')
      end

      it 'omits label when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('label')
      end
      it 'includes session when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(session: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('session')
      end

      it 'omits session when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('session')
      end
      it 'includes update when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(update: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('update')
      end

      it 'omits update when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('update')
      end
      it 'includes version when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(version: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('version')
      end

      it 'omits version when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('version')
      end
      it 'includes visible when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('opt', required_attrs.merge(visible: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'opt')
        expect(config).to have_key('visible')
      end

      it 'omits visible when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_apps_local', 'minimal')
        expect(config).not_to have_key('visible')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts configured=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(configured: val)
          synth.splunk_apps_local("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_apps_local', "bool_#{val}")
          expect(config['configured']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts filename=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(filename: val)
          synth.splunk_apps_local("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_apps_local', "bool_#{val}")
          expect(config['filename']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts update=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(update: val)
          synth.splunk_apps_local("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_apps_local', "bool_#{val}")
          expect(config['update']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts visible=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(visible: val)
          synth.splunk_apps_local("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_apps_local', "bool_#{val}")
          expect(config['visible']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_apps_local', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_apps_local('first', required_attrs)
        synth.splunk_apps_local('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_apps_local')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_apps_local,
    method: :splunk_apps_local,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :author, :configured, :description, :label, :version, :visible],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:configured, :filename, :update, :visible]
end
