# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_lookup_definition resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkLookupDefinition do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { filename: 'test-value', name: 'test-value' } }

  describe ':splunk_lookup_definition' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_definition('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_lookup_definition', 'test')
        validate_required_attributes(config, [:filename, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_lookup_definition('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_lookup_definition)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_lookup_definition('test', required_attrs)

        expect(ref.id).to eq("${splunk_lookup_definition.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_definition('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_lookup_definition', 'full')
        expect(config).to have_key('acl')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_definition('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_lookup_definition', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_definition('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_lookup_definition', 'minimal')
        expect(config).not_to have_key('acl')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_definition('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_lookup_definition', 'typed')
        expect(config['filename']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_definition('first', required_attrs)
        synth.splunk_lookup_definition('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_lookup_definition')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_lookup_definition,
    method: :splunk_lookup_definition,
    required_attrs: { filename: 'test-value', name: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
