# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_admin_saml_groups resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkAdminSamlGroups do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_admin_saml_groups' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_admin_saml_groups('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_admin_saml_groups', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_admin_saml_groups('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_admin_saml_groups)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_admin_saml_groups('test', required_attrs)

        expect(ref.id).to eq("${splunk_admin_saml_groups.test.id}")
        expect(ref.roles).to eq("${splunk_admin_saml_groups.test.roles}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_admin_saml_groups('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_admin_saml_groups', 'test')
        expect(config).not_to have_key('roles')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ roles: ['test-value'] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_admin_saml_groups('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_admin_saml_groups', 'full')
        expect(config).to have_key('roles')
      end
    end

    context 'optional attributes' do
      it 'includes roles when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_admin_saml_groups('opt', required_attrs.merge(roles: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_admin_saml_groups', 'opt')
        expect(config).to have_key('roles')
      end

      it 'omits roles when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_admin_saml_groups('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_admin_saml_groups', 'minimal')
        expect(config).not_to have_key('roles')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_admin_saml_groups('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_admin_saml_groups', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_admin_saml_groups('first', required_attrs)
        synth.splunk_admin_saml_groups('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_admin_saml_groups')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_admin_saml_groups,
    method: :splunk_admin_saml_groups,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :roles],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
