# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_sh_indexes_manager resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkShIndexesManager do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_sh_indexes_manager' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_sh_indexes_manager('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_sh_indexes_manager)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_sh_indexes_manager('test', required_attrs)

        expect(ref.id).to eq("${splunk_sh_indexes_manager.test.id}")
        expect(ref.datatype).to eq("${splunk_sh_indexes_manager.test.datatype}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'test')
        expect(config).not_to have_key('datatype')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, datatype: 'test-value', frozen_time_period_in_secs: 'test-value', max_global_raw_data_size_mb: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('datatype')
        expect(config).to have_key('frozen_time_period_in_secs')
        expect(config).to have_key('max_global_raw_data_size_mb')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes datatype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('opt', required_attrs.merge(datatype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'opt')
        expect(config).to have_key('datatype')
      end

      it 'omits datatype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'minimal')
        expect(config).not_to have_key('datatype')
      end
      it 'includes frozen_time_period_in_secs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('opt', required_attrs.merge(frozen_time_period_in_secs: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'opt')
        expect(config).to have_key('frozen_time_period_in_secs')
      end

      it 'omits frozen_time_period_in_secs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'minimal')
        expect(config).not_to have_key('frozen_time_period_in_secs')
      end
      it 'includes max_global_raw_data_size_mb when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('opt', required_attrs.merge(max_global_raw_data_size_mb: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'opt')
        expect(config).to have_key('max_global_raw_data_size_mb')
      end

      it 'omits max_global_raw_data_size_mb when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'minimal')
        expect(config).not_to have_key('max_global_raw_data_size_mb')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_sh_indexes_manager', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_sh_indexes_manager('first', required_attrs)
        synth.splunk_sh_indexes_manager('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_sh_indexes_manager')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_sh_indexes_manager,
    method: :splunk_sh_indexes_manager,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :datatype],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
