# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_lookup_table_file resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkLookupTableFile do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { app: 'test-value', file_contents: [['test-value']], file_name: 'test-value', owner: 'test-value' } }

  describe ':splunk_lookup_table_file' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_table_file('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_lookup_table_file', 'test')
        validate_required_attributes(config, [:app, :file_contents, :file_name, :owner])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_lookup_table_file('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_lookup_table_file)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_lookup_table_file('test', required_attrs)

        expect(ref.id).to eq("${splunk_lookup_table_file.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_table_file('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_lookup_table_file', 'typed')
        expect(config['app']).to be_a(String)
        expect(config['file_contents']).to be_a(Array)
        expect(config['file_name']).to be_a(String)
        expect(config['owner']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_lookup_table_file('first', required_attrs)
        synth.splunk_lookup_table_file('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_lookup_table_file')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_lookup_table_file,
    method: :splunk_lookup_table_file,
    required_attrs: { app: 'test-value', file_contents: [['test-value']], file_name: 'test-value', owner: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
