# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_inputs_tcp_raw resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkInputsTcpRaw do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':splunk_inputs_tcp_raw' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_tcp_raw('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_inputs_tcp_raw)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_tcp_raw('test', required_attrs)

        expect(ref.id).to eq("${splunk_inputs_tcp_raw.test.id}")
        expect(ref.connection_host).to eq("${splunk_inputs_tcp_raw.test.connection_host}")
        expect(ref.disabled).to eq("${splunk_inputs_tcp_raw.test.disabled}")
        expect(ref.host).to eq("${splunk_inputs_tcp_raw.test.host}")
        expect(ref.index).to eq("${splunk_inputs_tcp_raw.test.index}")
        expect(ref.queue).to eq("${splunk_inputs_tcp_raw.test.queue}")
        expect(ref.raw_tcp_done_timeout).to eq("${splunk_inputs_tcp_raw.test.raw_tcp_done_timeout}")
        expect(ref.restrict_to_host).to eq("${splunk_inputs_tcp_raw.test.restrict_to_host}")
        expect(ref.source).to eq("${splunk_inputs_tcp_raw.test.source}")
        expect(ref.sourcetype).to eq("${splunk_inputs_tcp_raw.test.sourcetype}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'test')
        expect(config).not_to have_key('connection_host')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('index')
        expect(config).not_to have_key('queue')
        expect(config).not_to have_key('raw_tcp_done_timeout')
        expect(config).not_to have_key('restrict_to_host')
        expect(config).not_to have_key('source')
        expect(config).not_to have_key('sourcetype')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, connection_host: 'test-value', disabled: true, host: 'test-value', index: 'test-value', queue: 'test-value', raw_tcp_done_timeout: 3.14, restrict_to_host: 'test-value', source: 'test-value', sourcetype: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('connection_host')
        expect(config).to have_key('disabled')
        expect(config).to have_key('host')
        expect(config).to have_key('index')
        expect(config).to have_key('queue')
        expect(config).to have_key('raw_tcp_done_timeout')
        expect(config).to have_key('restrict_to_host')
        expect(config).to have_key('source')
        expect(config).to have_key('sourcetype')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes connection_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(connection_host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('connection_host')
      end

      it 'omits connection_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('connection_host')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes index when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(index: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('index')
      end

      it 'omits index when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('index')
      end
      it 'includes queue when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(queue: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('queue')
      end

      it 'omits queue when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('queue')
      end
      it 'includes raw_tcp_done_timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(raw_tcp_done_timeout: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('raw_tcp_done_timeout')
      end

      it 'omits raw_tcp_done_timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('raw_tcp_done_timeout')
      end
      it 'includes restrict_to_host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(restrict_to_host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('restrict_to_host')
      end

      it 'omits restrict_to_host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('restrict_to_host')
      end
      it 'includes source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(source: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('source')
      end

      it 'omits source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('source')
      end
      it 'includes sourcetype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('opt', required_attrs.merge(sourcetype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'opt')
        expect(config).to have_key('sourcetype')
      end

      it 'omits sourcetype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'minimal')
        expect(config).not_to have_key('sourcetype')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_inputs_tcp_raw("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_tcp_raw', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_tcp_raw('first', required_attrs)
        synth.splunk_inputs_tcp_raw('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_inputs_tcp_raw')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_inputs_tcp_raw,
    method: :splunk_inputs_tcp_raw,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :connection_host, :disabled, :host, :index, :queue, :raw_tcp_done_timeout, :restrict_to_host, :source, :sourcetype],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled]
end
