# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a splunk_inputs_script resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::SplunkInputsScript do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { interval: 3.14, name: 'test-value' } }

  describe ':splunk_inputs_script' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'test')
        validate_required_attributes(config, [:interval, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_script('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:splunk_inputs_script)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.splunk_inputs_script('test', required_attrs)

        expect(ref.id).to eq("${splunk_inputs_script.test.id}")
        expect(ref.disabled).to eq("${splunk_inputs_script.test.disabled}")
        expect(ref.host).to eq("${splunk_inputs_script.test.host}")
        expect(ref.index).to eq("${splunk_inputs_script.test.index}")
        expect(ref.passauth).to eq("${splunk_inputs_script.test.passauth}")
        expect(ref.rename_source).to eq("${splunk_inputs_script.test.rename_source}")
        expect(ref.source).to eq("${splunk_inputs_script.test.source}")
        expect(ref.sourcetype).to eq("${splunk_inputs_script.test.sourcetype}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_script', 'test')
        expect(config).not_to have_key('disabled')
        expect(config).not_to have_key('host')
        expect(config).not_to have_key('index')
        expect(config).not_to have_key('passauth')
        expect(config).not_to have_key('rename_source')
        expect(config).not_to have_key('source')
        expect(config).not_to have_key('sourcetype')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ acl: { 'key1' => 'val1' }, disabled: true, host: 'test-value', index: 'test-value', passauth: 'test-value', rename_source: 'test-value', source: 'test-value', sourcetype: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_script', 'full')
        expect(config).to have_key('acl')
        expect(config).to have_key('disabled')
        expect(config).to have_key('host')
        expect(config).to have_key('index')
        expect(config).to have_key('passauth')
        expect(config).to have_key('rename_source')
        expect(config).to have_key('source')
        expect(config).to have_key('sourcetype')
      end
    end

    context 'optional attributes' do
      it 'includes acl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(acl: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('acl')
      end

      it 'omits acl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('acl')
      end
      it 'includes disabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(disabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('disabled')
      end

      it 'omits disabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('disabled')
      end
      it 'includes host when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(host: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('host')
      end

      it 'omits host when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('host')
      end
      it 'includes index when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(index: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('index')
      end

      it 'omits index when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('index')
      end
      it 'includes passauth when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(passauth: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('passauth')
      end

      it 'omits passauth when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('passauth')
      end
      it 'includes rename_source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(rename_source: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('rename_source')
      end

      it 'omits rename_source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('rename_source')
      end
      it 'includes source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(source: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('source')
      end

      it 'omits source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('source')
      end
      it 'includes sourcetype when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('opt', required_attrs.merge(sourcetype: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'opt')
        expect(config).to have_key('sourcetype')
      end

      it 'omits sourcetype when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'splunk_inputs_script', 'minimal')
        expect(config).not_to have_key('sourcetype')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts disabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disabled: val)
          synth.splunk_inputs_script("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'splunk_inputs_script', "bool_#{val}")
          expect(config['disabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'splunk_inputs_script', 'typed')
        expect(config['interval']).to be_a(Float)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.splunk_inputs_script('first', required_attrs)
        synth.splunk_inputs_script('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'splunk_inputs_script')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :splunk_inputs_script,
    method: :splunk_inputs_script,
    required_attrs: { interval: 3.14, name: 'test-value' },
    expected_outputs: [:id, :disabled, :host, :index, :passauth, :rename_source, :source, :sourcetype],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:disabled]
end
